SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `auth_tokens`;
CREATE TABLE `auth_tokens` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `token` varchar(128) NOT NULL,
  `type` enum('verify_email','reset_password') NOT NULL,
  `expires_at` timestamp NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `bots`;
CREATE TABLE `bots` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `platform` enum('telegram','discord','slack','whatsapp','twitch','matrix','reddit','mastodon','multi','other') DEFAULT 'telegram',
  `description` text DEFAULT NULL,
  `coolify_service_uuid` varchar(255) DEFAULT NULL,
  `coolify_app_uuid` varchar(255) DEFAULT NULL,
  `coolify_status` varchar(50) DEFAULT 'stopped',
  `env_vars` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`env_vars`)),
  `code_uploaded` tinyint(1) DEFAULT 0,
  `code_path` varchar(500) DEFAULT NULL,
  `docker_image` varchar(255) DEFAULT 'python:3.11-slim',
  `template_id` int(11) DEFAULT NULL,
  `auto_update` tinyint(1) NOT NULL DEFAULT 1,
  `current_version` varchar(20) NOT NULL DEFAULT '1.0.0',
  `last_updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `bots` (`id`, `user_id`, `name`, `platform`, `description`, `coolify_service_uuid`, `coolify_app_uuid`, `coolify_status`, `env_vars`, `code_uploaded`, `code_path`, `docker_image`, `template_id`, `auto_update`, `current_version`, `last_updated_at`, `created_at`, `updated_at`) VALUES
(8, 1, 'python-telegram-bot — Framework Telegram', 'telegram', 'Framework Python de referencia para bots Telegram.', NULL, 'di5nxwi7dyh5iparfnck3flz', 'running:unknown', '{\"TELEGRAM_BOT_TOKEN\":\"8733762121:AAG7eP0iPMEg_BhYLgpbOySUsWsLZ4I3xl0\"}', 0, NULL, 'python:3.11-slim', 64, 1, '1.0.0', NULL, '2026-04-14 21:21:28', '2026-04-14 21:22:06');

DROP TABLE IF EXISTS `bot_templates`;
CREATE TABLE `bot_templates` (
  `id` int(11) NOT NULL,
  `slug` varchar(80) NOT NULL,
  `name` varchar(150) NOT NULL,
  `description` text NOT NULL,
  `short_description` varchar(255) NOT NULL DEFAULT '',
  `platform` enum('telegram','discord','slack','whatsapp','twitch','matrix','reddit','mastodon','multi','other') DEFAULT 'telegram',
  `category` varchar(50) NOT NULL DEFAULT 'utility',
  `icon` varchar(10) NOT NULL DEFAULT '?',
  `docker_image` varchar(255) NOT NULL DEFAULT 'python:3.11-slim',
  `git_repo_url` varchar(500) DEFAULT NULL,
  `install_command` varchar(1000) DEFAULT NULL,
  `git_branch` varchar(100) DEFAULT 'main',
  `default_env_vars` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Env vars por defecto con claves y valores de ejemplo' CHECK (json_valid(`default_env_vars`)),
  `required_env_vars` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Array de objetos {key, label, placeholder, required}' CHECK (json_valid(`required_env_vars`)),
  `ram_mb_min` int(11) NOT NULL DEFAULT 128,
  `min_plan_slug` varchar(50) NOT NULL DEFAULT 'free',
  `difficulty` enum('easy','medium','advanced') DEFAULT 'easy',
  `tags` varchar(500) DEFAULT '',
  `documentation_url` varchar(500) DEFAULT NULL,
  `more_info_url` varchar(500) DEFAULT NULL,
  `setup_instructions` text DEFAULT NULL COMMENT 'Instrucciones paso a paso en texto plano',
  `needs_storage` tinyint(1) NOT NULL DEFAULT 0,
  `storage_mount_path` varchar(255) DEFAULT NULL,
  `starter_filename` varchar(100) DEFAULT NULL,
  `start_command` text DEFAULT NULL,
  `docs_first_steps_url` varchar(500) DEFAULT NULL,
  `is_featured` tinyint(1) DEFAULT 0,
  `is_active` tinyint(1) DEFAULT 1,
  `install_count` int(10) UNSIGNED DEFAULT 0,
  `auto_update_supported` tinyint(1) NOT NULL DEFAULT 1,
  `version` varchar(20) NOT NULL DEFAULT '1.0.0',
  `changelog` text DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `bot_templates` (`id`, `slug`, `name`, `description`, `short_description`, `platform`, `category`, `icon`, `docker_image`, `git_repo_url`, `install_command`, `git_branch`, `default_env_vars`, `required_env_vars`, `ram_mb_min`, `min_plan_slug`, `difficulty`, `tags`, `documentation_url`, `more_info_url`, `setup_instructions`, `needs_storage`, `storage_mount_path`, `starter_filename`, `start_command`, `docs_first_steps_url`, `is_featured`, `is_active`, `install_count`, `auto_update_supported`, `version`, `changelog`, `sort_order`, `created_at`, `updated_at`) VALUES
(2, 'discord-music-bot', 'Discord Music Bot', 'Bot de Discord que reproduce música de YouTube en canales de voz. Usa discord.js y yt-dlp para streaming de audio en tiempo real. Comandos: !play, !skip, !stop, !queue, !pause, !resume. Cola de reproducción con lista de espera.', 'Reproduce música de YouTube en tu servidor de Discord.', 'discord', 'entertainment', '🎵', 'node:20-alpine', 'https://github.com/eritislami/evobot', NULL, 'master', '{\"DISCORD_TOKEN\": \"\", \"PREFIX\": \"!\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2Nzg5MDEyMzQ1Njc4.Gabcde.XXXXXX\", \"required\": true}, {\"key\": \"PREFIX\", \"label\": \"Prefijo de comandos\", \"placeholder\": \"!\", \"required\": false}]', 256, 'starter', 'easy', 'discord,music,youtube,nodejs,entretenimiento', NULL, 'https://github.com/eritislami/evobot', '1. Ve a https://discord.com/developers/applications y crea una aplicación\n2. En la sección Bot, copia el Token\n3. Activa los intents: Message Content, Server Members\n4. Invita el bot a tu servidor con permisos de voz\n5. Pega el token en DISCORD_TOKEN\n6. Despliega y usa !play <url> en un canal de voz', 0, NULL, NULL, NULL, NULL, 1, 0, 1, 1, '1.0.0', NULL, 2, '2026-03-31 10:58:55', '2026-04-11 20:48:57'),
(3, 'telegram-gpt-bot', 'Telegram AI Chat (GPT)', 'Bot de Telegram potenciado con la API de OpenAI (GPT-4o / GPT-3.5). Responde preguntas, genera texto, traduce, resume y mucho más. Mantiene contexto de conversación por usuario. Configurable con system prompt personalizado.', 'Asistente IA en Telegram con ChatGPT integrado.', 'telegram', 'ai', '🧠', 'python:3.11-slim', 'https://github.com/father-bot/chatgpt_telegram_bot', 'sed -i \"s/PyYAML==6.0$/PyYAML>=6.0.1/\" requirements.txt', 'main', '{\"BOT_TOKEN\": \"\", \"OPENAI_API_KEY\": \"\", \"OPENAI_MODEL\": \"gpt-4o-mini\", \"SYSTEM_PROMPT\": \"Eres un asistente útil y amigable.\"}', '[{\"key\": \"BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}, {\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key de OpenAI\", \"placeholder\": \"sk-...\", \"required\": true}, {\"key\": \"OPENAI_MODEL\", \"label\": \"Modelo de OpenAI\", \"placeholder\": \"gpt-4o-mini\", \"required\": false}]', 256, 'starter', 'easy', 'telegram,gpt,openai,chatgpt,ia,inteligencia-artificial', NULL, 'https://github.com/karfly/chatgpt_telegram_bot', '1. Crea un bot en Telegram con @BotFather y copia el token\n2. Obtén una API Key en https://platform.openai.com/api-keys\n3. Rellena BOT_TOKEN y OPENAI_API_KEY\n4. Opcionalmente personaliza el SYSTEM_PROMPT\n5. Despliega y empieza a chatear con tu bot IA', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 3, '2026-03-31 10:58:55', '2026-04-14 22:29:38'),
(4, 'discord-mod-bot', 'Discord Moderación Bot', 'Bot de moderación automática para servidores de Discord. Detecta spam, palabras prohibidas, raid de cuentas nuevas y flood de mensajes. Comandos: !ban, !kick, !mute, !warn, !purge. Sistema de warns con escalado automático. Logs de moderación en canal dedicado.', 'Modera tu servidor de Discord automáticamente.', 'discord', 'moderation', '🛡️', 'node:20-alpine', 'https://github.com/jagrosh/Vortex', NULL, 'master', '{\"DISCORD_TOKEN\": \"\", \"PREFIX\": \"!\", \"MOD_LOG_CHANNEL\": \"\", \"WARN_THRESHOLD\": \"3\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}, {\"key\": \"MOD_LOG_CHANNEL\", \"label\": \"ID del canal de logs\", \"placeholder\": \"123456789012345678\", \"required\": false}]', 256, 'starter', 'medium', 'discord,moderacion,antispam,seguridad,nodejs', NULL, 'https://github.com/jagrosh/Vortex', '1. Crea una aplicación en Discord Developer Portal\n2. Crea el bot y copia el token\n3. Activa intents: Message Content, Server Members, Moderation\n4. Invita con permisos de administrador\n5. Configura DISCORD_TOKEN y opcionalmente MOD_LOG_CHANNEL\n6. Despliega el bot', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 4, '2026-03-31 10:58:55', '2026-04-11 20:48:57'),
(8, 'telegram-rss-bot', 'Telegram RSS Feed Bot', 'Bot de Telegram que monitorea feeds RSS/Atom y envía notificaciones automáticas cuando hay contenido nuevo. Ideal para seguir blogs, noticias, canales de YouTube, podcasts o cualquier fuente con RSS. Soporta múltiples feeds y filtros por palabras clave.', 'Monitorea feeds RSS y notifica en Telegram.', 'telegram', 'utility', '📡', 'python:3.11-slim', 'https://github.com/Rongronggg9/RSS-to-Telegram-Bot', NULL, 'main', '{\"BOT_TOKEN\": \"\", \"CHAT_ID\": \"\", \"RSS_URLS\": \"https://feeds.example.com/rss\", \"CHECK_INTERVAL\": \"300\"}', '[{\"key\": \"BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}, {\"key\": \"CHAT_ID\", \"label\": \"ID del chat/canal donde enviar\", \"placeholder\": \"-1001234567890\", \"required\": true}, {\"key\": \"RSS_URLS\", \"label\": \"URLs de feeds RSS (separados por coma)\", \"placeholder\": \"https://blog.example.com/feed\", \"required\": true}]', 128, 'free', 'medium', 'telegram,rss,feed,noticias,notificaciones,python', NULL, 'https://github.com/Rongronggg9/RSS-to-Telegram-Bot', '1. Crea un bot con @BotFather\n2. Añade el bot a un grupo o canal como admin\n3. Obtén el CHAT_ID del grupo (usa @raw_data_bot)\n4. Introduce las URLs de los feeds RSS que quieres seguir\n5. Ajusta CHECK_INTERVAL (en segundos, por defecto 300 = 5 min)\n6. Despliega y recibirás noticias automáticamente', 0, NULL, NULL, NULL, NULL, 0, 0, 0, 1, '1.0.0', NULL, 8, '2026-03-31 10:58:55', '2026-04-11 20:48:57'),
(9, 'discord-ticket-bot', 'Discord Tickets / Soporte Bot', 'Sistema de tickets de soporte para Discord. Los usuarios abren tickets con un botón o comando, se crea un canal privado para la conversación. Incluye: transcripciones, categorías de tickets, panel de estadísticas, cierre automático por inactividad y notificaciones al staff.', 'Sistema de soporte con tickets para Discord.', 'discord', 'utility', '🎫', 'node:20-alpine', 'https://github.com/discord-tickets/bot', NULL, 'master', '{\"DISCORD_TOKEN\": \"\", \"PREFIX\": \"!\", \"SUPPORT_ROLE_ID\": \"\", \"TICKET_CATEGORY_ID\": \"\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}, {\"key\": \"SUPPORT_ROLE_ID\", \"label\": \"ID del rol de soporte\", \"placeholder\": \"123456789012345678\", \"required\": true}]', 256, 'starter', 'medium', 'discord,tickets,soporte,support,helpdesk,nodejs', NULL, 'https://discordtickets.app', '1. Crea aplicación y bot en Discord Developer Portal\n2. Activa intents necesarios\n3. Crea un rol @Soporte y una categoría para tickets\n4. Copia los IDs del rol y la categoría\n5. Configura DISCORD_TOKEN, SUPPORT_ROLE_ID y TICKET_CATEGORY_ID\n6. Despliega y usa !ticket para abrir un ticket', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 9, '2026-03-31 10:58:55', '2026-04-11 20:48:57'),
(17, 'uptime-monitor-bot', 'Monitor de Uptime', 'Bot que monitorea la disponibilidad de tus sitios web y servicios. Hace ping periódico a URLs configuradas y envía alertas por Telegram, Discord, Slack o email cuando detecta caídas. Dashboard con historial de uptime, tiempos de respuesta y estadísticas. Reportes diarios/semanales opcionales.', 'Monitorea tus webs y recibe alertas de caídas.', 'multi', 'monitoring', '📊', 'node:20-alpine', 'https://github.com/louislam/uptime-kuma', NULL, 'main', '{\"URLS_TO_MONITOR\": \"\", \"CHECK_INTERVAL\": \"60\", \"ALERT_TELEGRAM_TOKEN\": \"\", \"ALERT_TELEGRAM_CHAT_ID\": \"\", \"ALERT_DISCORD_WEBHOOK\": \"\"}', '[{\"key\": \"URLS_TO_MONITOR\", \"label\": \"URLs a monitorear (una por línea o separadas por coma)\", \"placeholder\": \"https://miapp.com, https://api.miapp.com\", \"required\": true}, {\"key\": \"CHECK_INTERVAL\", \"label\": \"Intervalo de comprobación (segundos)\", \"placeholder\": \"60\", \"required\": false}, {\"key\": \"ALERT_TELEGRAM_TOKEN\", \"label\": \"Token de Telegram para alertas (opcional)\", \"placeholder\": \"123456:ABC...\", \"required\": false}, {\"key\": \"ALERT_DISCORD_WEBHOOK\", \"label\": \"Webhook de Discord para alertas (opcional)\", \"placeholder\": \"https://discord.com/api/webhooks/...\", \"required\": false}]', 128, 'free', 'easy', 'monitor,uptime,alertas,web,ping,multi', NULL, 'https://uptime.kuma.pet', '1. Lista las URLs que quieres monitorear\n2. Configura al menos un canal de alertas (Telegram o Discord)\n3. Ajusta el intervalo de comprobación (por defecto 60 seg)\n4. Despliega y recibirás alertas cuando una URL no responda\n5. Consulta /status para ver el dashboard', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 17, '2026-04-06 19:22:49', '2026-04-11 20:48:57'),
(28, 'n8n-automation-bot', 'n8n Automatización de Flujos', 'n8n es una plataforma de automatización de flujos de trabajo (como Zapier pero self-hosted). Conecta más de 400 servicios: Gmail, Sheets, Slack, Telegram, GitHub, Shopify, Stripe, etc. Interfaz visual drag-and-drop para crear automatizaciones sin código.', 'Automatiza flujos de trabajo como Zapier, self-hosted.', 'multi', 'developer', '⚡', 'n8nio/n8n:latest', 'https://github.com/n8n-io/n8n', NULL, 'main', '{\"N8N_BASIC_AUTH_ACTIVE\": \"true\", \"N8N_BASIC_AUTH_USER\": \"admin\", \"N8N_BASIC_AUTH_PASSWORD\": \"\", \"WEBHOOK_URL\": \"\", \"TIMEZONE\": \"Europe/Madrid\"}', '[{\"key\": \"N8N_BASIC_AUTH_PASSWORD\", \"label\": \"Contraseña del panel de n8n\", \"placeholder\": \"tu_contraseña_segura\", \"required\": true}, {\"key\": \"WEBHOOK_URL\", \"label\": \"URL pública del servicio (para webhooks)\", \"placeholder\": \"https://n8n.midominio.com\", \"required\": false}]', 512, 'medium', 'medium', 'n8n,automatizacion,workflow,zapier,integracion,nocode,multi', NULL, 'https://n8n.io', '1. Elige una contraseña segura para el panel de administración\n2. Despliega n8n\n3. Accede al panel web con las credenciales configuradas\n4. Crea tu primer flujo de trabajo arrastrando y conectando nodos\n5. Conecta servicios con sus API keys desde el panel', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 28, '2026-04-06 20:31:39', '2026-04-11 20:48:57'),
(29, 'discord-lavalink-bot', 'Discord Música Avanzada (Lavalink)', 'Bot de música avanzado para Discord con Lavalink como backend de audio. Soporta YouTube, Spotify, SoundCloud, Deezer, Apple Music y más. Ecualizador, filtros de audio (bass boost, nightcore, 8D), letras, cola ilimitada y playlists guardadas.', 'Música avanzada con Spotify, filtros y ecualizador.', 'discord', 'entertainment', '🎶', 'node:20-alpine', 'https://github.com/stegripe/rawon', NULL, 'main', '{\"DISCORD_TOKEN\": \"\", \"LAVALINK_HOST\": \"localhost\", \"LAVALINK_PORT\": \"2333\", \"LAVALINK_PASSWORD\": \"youshallnotpass\", \"SPOTIFY_CLIENT_ID\": \"\", \"SPOTIFY_CLIENT_SECRET\": \"\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}, {\"key\": \"SPOTIFY_CLIENT_ID\", \"label\": \"Spotify Client ID (opcional)\", \"placeholder\": \"abc123...\", \"required\": false}, {\"key\": \"SPOTIFY_CLIENT_SECRET\", \"label\": \"Spotify Client Secret (opcional)\", \"placeholder\": \"xyz789...\", \"required\": false}]', 512, 'medium', 'advanced', 'discord,musica,lavalink,spotify,soundcloud,ecualizador,nodejs', NULL, 'https://github.com/stegripe/rawon', '1. Crea una app y bot en Discord Developer Portal\n2. Activa intents: Message Content, Voice\n3. Opcionalmente crea una app en Spotify Developer\n4. Configura los tokens\n5. Despliega (Lavalink se incluye internamente)\n6. Usa /play <canción> para reproducir', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 29, '2026-04-06 20:31:39', '2026-04-11 20:48:57'),
(30, 'telegram-trading-bot', 'Telegram Señales de Trading Bot', 'Bot de Telegram que analiza mercados y envía señales de trading basadas en indicadores técnicos (RSI, MACD, Bollinger Bands, EMA). Soporta crypto y forex. Alertas por niveles de precio, volumen anormal y cruces de medias. Backtest incluido.', 'Señales de trading y análisis técnico automatizado.', 'telegram', 'finance', '📊', 'python:3.11-slim', 'https://github.com/freqtrade/freqtrade', NULL, 'main', '{\"BOT_TOKEN\": \"\", \"EXCHANGE\": \"binance\", \"TRADING_PAIRS\": \"BTC/USDT,ETH/USDT\", \"TIMEFRAME\": \"1h\", \"RSI_PERIOD\": \"14\"}', '[{\"key\": \"BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}, {\"key\": \"TRADING_PAIRS\", \"label\": \"Pares de trading (separados por coma)\", \"placeholder\": \"BTC/USDT,ETH/USDT\", \"required\": true}]', 256, 'starter', 'medium', 'telegram,trading,crypto,forex,señales,indicadores,finanzas,python', NULL, 'https://www.freqtrade.io', '1. Crea un bot con @BotFather\n2. Define los pares de trading que quieres analizar\n3. Elige el exchange (binance, kraken, etc.)\n4. Configura el intervalo de análisis\n5. Despliega y recibe señales en tu chat', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 30, '2026-04-06 20:31:39', '2026-04-11 20:48:57'),
(32, 'telegram-pdf-bot', 'Telegram Herramientas PDF Bot', 'Bot de Telegram para trabajar con PDFs. Convierte imágenes a PDF, une varios PDFs, comprime archivos pesados, extrae texto (OCR), añade marcas de agua, protege con contraseña y convierte PDF a Word/imágenes. Todo gratis y sin límites.', 'Convierte, une, comprime y edita PDFs desde Telegram.', 'telegram', 'productivity', '📄', 'python:3.11-slim', 'https://github.com/zeshuaro/telegram-pdf-bot', NULL, 'main', '{\"BOT_TOKEN\": \"\", \"MAX_FILE_SIZE_MB\": \"50\", \"LANGUAGE\": \"es\"}', '[{\"key\": \"BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 256, 'free', 'easy', 'telegram,pdf,convertir,comprimir,ocr,herramientas,python', NULL, 'https://github.com/zeshuaro/telegram-pdf-bot', '1. Crea un bot con @BotFather\n2. Configura el token\n3. Despliega el bot\n4. Envía archivos PDF o imágenes al bot\n5. Elige la operación: unir, comprimir, convertir, etc.', 0, NULL, NULL, NULL, NULL, 1, 0, 0, 1, '1.0.0', NULL, 32, '2026-04-06 20:31:39', '2026-04-11 20:48:57'),
(51, 'n8n', 'n8n — Automatización de Flujos IA', 'Plataforma de automatización de flujos de trabajo con capacidades nativas de IA para crear agentes complejos sin código. Conecta más de 400 servicios (Gmail, Sheets, Slack, Telegram, GitHub, Shopify, Stripe). Interfaz visual drag-and-drop.', 'Automatiza flujos de trabajo como Zapier, self-hosted con IA.', 'multi', 'ai', '⚡', 'n8nio/n8n:latest', NULL, NULL, 'main', '{\"N8N_BASIC_AUTH_ACTIVE\": \"true\", \"N8N_BASIC_AUTH_USER\": \"admin\", \"N8N_BASIC_AUTH_PASSWORD\": \"\", \"GENERIC_TIMEZONE\": \"Europe/Madrid\"}', '[{\"key\": \"N8N_BASIC_AUTH_PASSWORD\", \"label\": \"Contraseña del panel de n8n\", \"placeholder\": \"tu_contraseña_segura\", \"required\": true}]', 512, 'medium', 'medium', 'n8n,automatizacion,workflow,zapier,ia,agentes,nocode,multi', NULL, 'https://n8n.io/', '1. Elige una contraseña segura para el panel\n2. Despliega n8n\n3. Accede al panel web con usuario admin y tu contraseña\n4. Crea flujos arrastrando y conectando nodos\n5. Conecta servicios con sus API keys desde el panel\n\n📖 Primeros pasos: https://docs.n8n.io/try-it-out/', 1, '/home/node/.n8n', NULL, NULL, 'https://docs.n8n.io/try-it-out/', 1, 1, 0, 1, '1.0.0', NULL, 1, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(52, 'dify', 'Dify — Plataforma LLM y Agentes', 'Marco de desarrollo de aplicaciones LLM que permite orquestar flujos de agentes, gestionar conjuntos de datos y realizar despliegues rápidos con interfaz visual intuitiva. Soporta RAG, function calling y múltiples modelos.', 'Orquesta agentes IA y aplicaciones LLM con interfaz visual.', 'multi', 'ai', '🤖', 'langgenius/dify-api:latest', 'https://github.com/langgenius/dify', NULL, 'main', '{\"SECRET_KEY\": \"\", \"OPENAI_API_KEY\": \"\", \"LOG_LEVEL\": \"INFO\"}', '[{\"key\": \"SECRET_KEY\", \"label\": \"Clave secreta de la aplicación\", \"placeholder\": \"sk-...\", \"required\": true}, {\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key de OpenAI (u otro proveedor)\", \"placeholder\": \"sk-...\", \"required\": true}]', 2048, 'pro', 'advanced', 'dify,llm,agentes,ia,rag,chatbot,openai,multi', NULL, 'https://dify.ai/', '1. Genera una SECRET_KEY aleatoria\n2. Obtén una API Key de OpenAI u otro proveedor LLM\n3. Despliega Dify (requiere Redis y PostgreSQL como servicios adjuntos)\n4. Accede al panel web para crear aplicaciones de IA\n5. Configura modelos y bases de conocimiento desde la interfaz\n\n📖 Primeros pasos: https://docs.dify.ai/getting-started/install-self-hosted/docker-compose', 1, '/app/api/storage', NULL, NULL, 'https://docs.dify.ai/getting-started/install-self-hosted/docker-compose', 1, 1, 0, 1, '1.0.0', NULL, 2, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(53, 'langflow', 'Langflow — Flujos LangChain Visual', 'Herramienta visual de bajo código para experimentar y desplegar flujos basados en LangChain. Permite iteración rápida de prototipos de IA con interfaz drag-and-drop para cadenas, agentes y herramientas.', 'Crea flujos de IA con LangChain visualmente.', 'multi', 'ai', '🔗', 'langflowai/langflow:latest', NULL, NULL, 'main', '{\"LANGFLOW_DATABASE_URL\": \"sqlite:///./langflow.db\", \"OPENAI_API_KEY\": \"\"}', '[{\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key de OpenAI\", \"placeholder\": \"sk-...\", \"required\": true}]', 1024, 'medium', 'medium', 'langflow,langchain,ia,visual,flujos,prototipo,multi', NULL, 'https://www.langflow.org/', '1. Obtén una API Key de OpenAI\n2. Despliega Langflow\n3. Accede a la interfaz web\n4. Arrastra componentes para crear flujos de IA\n5. Prueba y despliega tus cadenas LangChain\n\n📖 Primeros pasos: https://docs.langflow.org/get-started-installation', 1, '/app/langflow', NULL, NULL, 'https://docs.langflow.org/get-started-installation', 1, 1, 0, 1, '1.0.0', NULL, 3, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(54, 'anythingllm', 'AnythingLLM — Base de Conocimiento IA', 'Solución integral para convertir documentos en una base de conocimientos privada e interactuar con diversos modelos de lenguaje. Soporta RAG, chat con documentos, múltiples proveedores LLM y gestión de workspaces.', 'Chat privado con tus documentos usando cualquier LLM.', 'multi', 'ai', '📚', 'mintplexlabs/anythingllm:latest', NULL, NULL, 'main', '{\"STORAGE_DIR\": \"/app/server/storage\", \"LLM_PROVIDER\": \"openai\", \"OPEN_AI_KEY\": \"\"}', '[{\"key\": \"OPEN_AI_KEY\", \"label\": \"API Key del proveedor LLM\", \"placeholder\": \"sk-...\", \"required\": true}]', 1024, 'medium', 'easy', 'anythingllm,documentos,rag,conocimiento,llm,privado,multi', NULL, 'https://useanything.com/', '1. Obtén una API Key de tu proveedor LLM preferido\n2. Despliega AnythingLLM\n3. Accede al panel web y crea un workspace\n4. Sube documentos (PDF, TXT, DOCX, etc.)\n5. Chatea con tus documentos usando IA\n\n📖 Primeros pasos: https://docs.useanything.com/installation/self-hosted/local-docker', 1, '/app/server/storage', NULL, NULL, 'https://docs.useanything.com/installation/self-hosted/local-docker', 1, 1, 0, 1, '1.0.0', NULL, 4, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(55, 'open-webui', 'Open WebUI — Interfaz ChatGPT Local', 'Interfaz de usuario similar a ChatGPT para modelos alojados localmente. Soporte para RAG, gestión multi-usuario, plugins, generación de imágenes y conexión con Ollama u APIs compatibles con OpenAI.', 'Interfaz tipo ChatGPT para modelos locales o APIs.', 'multi', 'ai', '💬', 'ghcr.io/open-webui/open-webui:main', NULL, NULL, 'main', '{\"OLLAMA_BASE_URL\": \"http://ollama:11434\", \"OPENAI_API_BASE_URL\": \"\", \"OPENAI_API_KEY\": \"\", \"WEBUI_SECRET_KEY\": \"\"}', '[{\"key\": \"WEBUI_SECRET_KEY\", \"label\": \"Clave secreta del panel\", \"placeholder\": \"clave_aleatoria_segura\", \"required\": true}, {\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key OpenAI (o compatible)\", \"placeholder\": \"sk-...\", \"required\": false}]', 1024, 'medium', 'easy', 'openwebui,chatgpt,ollama,interfaz,local,rag,multi', NULL, 'https://openwebui.com/', '1. Genera una clave secreta para el panel\n2. Opcionalmente configura conexión a Ollama o una API OpenAI-compatible\n3. Despliega Open WebUI\n4. Regístrate como primer usuario (será admin)\n5. Comienza a chatear con modelos de IA\n\n📖 Primeros pasos: https://docs.openwebui.com/getting-started/', 1, '/app/backend/data', NULL, NULL, 'https://docs.openwebui.com/getting-started/', 1, 1, 0, 1, '1.0.0', NULL, 5, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(56, 'ollama', 'Ollama — Servidor de Modelos LLM', 'Servidor de modelos de lenguaje grandes para ejecución local. Pieza fundamental para que otros bots ejecuten LLMs en tu propia infraestructura. Soporta Llama 3, Mistral, CodeLlama, Gemma y más.', 'Ejecuta modelos LLM localmente (Llama, Mistral, etc.).', 'multi', 'ai', '🦙', 'ollama/ollama:latest', NULL, NULL, 'main', '{\"OLLAMA_HOST\": \"0.0.0.0\", \"OLLAMA_MODELS\": \"/root/.ollama/models\"}', '[]', 4096, 'pro', 'medium', 'ollama,llm,local,modelos,llama,mistral,gpu,multi', NULL, 'https://ollama.com/', '1. Despliega Ollama (requiere plan Pro por alto consumo de RAM)\n2. Accede al servidor\n3. Ejecuta: ollama pull llama3 para descargar un modelo\n4. Conecta Open WebUI u otros servicios apuntando a este servidor\n5. Los modelos se almacenan en el volumen persistente\n\n📖 Primeros pasos: https://github.com/ollama/ollama#quickstart', 1, '/root/.ollama', NULL, NULL, 'https://github.com/ollama/ollama#quickstart', 1, 1, 0, 1, '1.0.0', NULL, 6, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(57, 'openclaw', 'OpenClaw — Asistente IA Personal', 'Asistente de IA personal y local que se integra con WhatsApp y Telegram. Ejecuta tareas de forma autónoma desde el chat: busca información, gestiona archivos, programa recordatorios y más.', '[DESACTIVADO] Asistente IA personal para WhatsApp y Telegram.', 'multi', 'ai', '🦀', 'python:3.11-slim', NULL, NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\", \"OPENAI_API_KEY\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": false}, {\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key de OpenAI\", \"placeholder\": \"sk-...\", \"required\": true}]', 512, 'medium', 'medium', 'openclaw,asistente,ia,personal,telegram,whatsapp,autonomo', NULL, 'https://github.com/BlockRunAI/OpenClaw', '1. Obtén una API Key de OpenAI\n2. Opcionalmente crea un bot en Telegram con @BotFather\n3. Configura las credenciales\n4. Despliega OpenClaw\n5. Interactúa con el asistente desde Telegram o WhatsApp\n\n📖 Primeros pasos: https://github.com/BlockRunAI/OpenClaw#readme', 0, NULL, NULL, NULL, 'https://github.com/BlockRunAI/OpenClaw#readme', 0, 0, 0, 1, '1.0.0', NULL, 7, '2026-04-11 20:48:57', '2026-04-14 22:29:38'),
(58, 'crewai', 'CrewAI — Equipos de Agentes IA', 'Framework para orquestar grupos de agentes de IA autónomos que trabajan en conjunto para resolver tareas complejas, simulando una estructura de equipo humano. Define roles, herramientas y objetivos para cada agente.', 'Orquesta equipos de agentes IA autónomos.', 'multi', 'ai', '👥', 'python:3.11-slim', 'https://github.com/crewAIInc/crewAI', 'pip install crewai', 'main', '{\"OPENAI_API_KEY\": \"\", \"CREWAI_TELEMETRY\": \"false\"}', '[{\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key de OpenAI\", \"placeholder\": \"sk-...\", \"required\": true}]', 512, 'medium', 'advanced', 'crewai,agentes,equipo,ia,autonomo,orquestacion,multi', NULL, 'https://www.crewai.com/', '1. Obtén una API Key de OpenAI\n2. Despliega CrewAI\n3. Define agentes con roles específicos (investigador, escritor, etc.)\n4. Asigna tareas y herramientas a cada agente\n5. Los agentes colaboran automáticamente para completar objetivos\n\n📖 Primeros pasos: https://docs.crewai.com/quickstart', 0, NULL, NULL, NULL, 'https://docs.crewai.com/quickstart', 1, 1, 0, 1, '1.0.0', NULL, 8, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(59, 'autogen', 'AutoGen (AG2) — Agentes Multi-conversación', 'Desarrollado por Microsoft, permite crear aplicaciones LLM basadas en múltiples agentes que conversan entre sí para completar objetivos específicos. Ideal para resolución de problemas complejos y generación de código.', 'Agentes IA de Microsoft que conversan entre sí.', 'multi', 'ai', '🔄', 'python:3.11-slim', 'https://github.com/microsoft/autogen', 'pip install autogen-agentchat', 'main', '{\"OPENAI_API_KEY\": \"\", \"OAI_CONFIG_LIST\": \"\"}', '[{\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key de OpenAI\", \"placeholder\": \"sk-...\", \"required\": true}]', 512, 'medium', 'advanced', 'autogen,microsoft,agentes,conversacion,llm,codigo,multi', NULL, 'https://microsoft.github.io/autogen/', '1. Obtén una API Key de OpenAI\n2. Despliega AutoGen\n3. Define agentes conversacionales con roles\n4. Los agentes interactúan entre sí para resolver tareas\n5. Ideal para generación de código y análisis complejos\n\n📖 Primeros pasos: https://microsoft.github.io/autogen/docs/Getting-Started', 0, NULL, NULL, NULL, 'https://microsoft.github.io/autogen/docs/Getting-Started', 0, 1, 0, 1, '1.0.0', NULL, 9, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(60, 'agentscope', 'AgentScope — Apps Multi-Agente', 'Marco centrado en el desarrollador para construir aplicaciones multi-agente robustas. Enfoque en facilidad de uso, interacciones robustas y soporte para múltiples proveedores de modelos LLM.', 'Framework de apps multi-agente para desarrolladores.', 'multi', 'ai', '🔬', 'python:3.11-slim', 'https://github.com/agentscope-ai/agentscope', 'pip install agentscope', 'main', '{\"OPENAI_API_KEY\": \"\", \"MODEL_CONFIG\": \"\"}', '[{\"key\": \"OPENAI_API_KEY\", \"label\": \"API Key del proveedor LLM\", \"placeholder\": \"sk-...\", \"required\": true}]', 512, 'medium', 'advanced', 'agentscope,modelscope,multi-agente,llm,developer,framework', NULL, 'https://github.com/modelscope/agentscope', '1. Obtén una API Key de tu proveedor LLM\n2. Despliega AgentScope\n3. Configura los modelos disponibles\n4. Crea aplicaciones multi-agente con el SDK\n5. Prueba las interacciones entre agentes\n\n📖 Primeros pasos: https://doc.agentscope.io/tutorial/quick_start.html', 0, NULL, NULL, NULL, 'https://doc.agentscope.io/tutorial/quick_start.html', 0, 1, 0, 1, '1.0.0', NULL, 10, '2026-04-11 20:48:57', '2026-04-14 22:29:38'),
(61, 'evolution-api', 'Evolution API — API REST para WhatsApp', 'Interfaz API REST para controlar cuentas de WhatsApp. Permite integraciones avanzadas con Typebot, Chatwoot y n8n. Envía y recibe mensajes, gestiona grupos, envía medios y más desde cualquier lenguaje.', 'API REST completa para automatizar WhatsApp.', 'whatsapp', 'communication', '📱', 'atendai/evolution-api:latest', NULL, NULL, 'main', '{\"AUTHENTICATION_API_KEY\": \"\", \"AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES\": \"true\", \"SERVER_PORT\": \"8080\"}', '[{\"key\": \"AUTHENTICATION_API_KEY\", \"label\": \"API Key de autenticación\", \"placeholder\": \"tu_api_key_segura\", \"required\": true}]', 256, 'starter', 'medium', 'evolution,whatsapp,api,rest,mensajes,integracion,chatwoot,n8n', NULL, 'https://evolution-api.com/', '1. Define una API Key de autenticación segura\n2. Despliega Evolution API\n3. Accede al panel web para vincular tu número de WhatsApp\n4. Escanea el QR con tu teléfono\n5. Usa la API REST para enviar/recibir mensajes\n\n📖 Primeros pasos: https://doc.evolution-api.com/v2/en/get-started/introduction', 1, '/evolution/instances', NULL, NULL, 'https://doc.evolution-api.com/v2/en/get-started/introduction', 1, 1, 0, 1, '1.0.0', NULL, 11, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(62, 'waha', 'WAHA — WhatsApp HTTP API', 'Solución lista para usar que expone funciones de WhatsApp mediante API REST. Facilita la creación de bots en cualquier lenguaje. Sesiones múltiples, webhooks, envío de medios, estados y gestión de contactos.', 'API HTTP para WhatsApp, lista para usar.', 'whatsapp', 'communication', '💚', 'devlikeapro/waha:latest', NULL, NULL, 'main', '{\"WHATSAPP_DEFAULT_ENGINE\": \"WEBJS\", \"WAHA_DASHBOARD_ENABLED\": \"true\", \"WAHA_DASHBOARD_USERNAME\": \"admin\", \"WAHA_DASHBOARD_PASSWORD\": \"\"}', '[{\"key\": \"WAHA_DASHBOARD_PASSWORD\", \"label\": \"Contraseña del panel WAHA\", \"placeholder\": \"contraseña_segura\", \"required\": true}]', 256, 'starter', 'easy', 'waha,whatsapp,http,api,bot,sesiones,webhooks', NULL, 'https://waha.devlikeapro.com/', '1. Define una contraseña para el panel\n2. Despliega WAHA\n3. Accede al dashboard web\n4. Inicia una sesión y escanea el QR\n5. Conecta tus aplicaciones mediante la API REST\n\n📖 Primeros pasos: https://waha.devlikeapro.com/docs/overview/quick-start/', 1, '/tmp/.sessions', NULL, NULL, 'https://waha.devlikeapro.com/docs/overview/quick-start/', 1, 1, 0, 1, '1.0.0', NULL, 12, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(63, 'matrix-nio', 'Matrix-nio — Bots para Matrix', 'Biblioteca Python de alto nivel para el protocolo Matrix, red descentralizada centrada en seguridad y soberanía del usuario. Ideal para construir bots de chat cifrados end-to-end en la red Matrix.', 'Framework Python para bots en Matrix (E2EE).', 'matrix', 'communication', '🟢', 'python:3.11-slim', NULL, NULL, 'main', '{\"MATRIX_HOMESERVER\": \"\", \"MATRIX_USER_ID\": \"\", \"MATRIX_PASSWORD\": \"\", \"MATRIX_ROOM_ID\": \"\"}', '[{\"key\": \"MATRIX_HOMESERVER\", \"label\": \"URL del homeserver Matrix\", \"placeholder\": \"https://matrix.org\", \"required\": true}, {\"key\": \"MATRIX_USER_ID\", \"label\": \"ID de usuario Matrix\", \"placeholder\": \"@bot:matrix.org\", \"required\": true}, {\"key\": \"MATRIX_PASSWORD\", \"label\": \"Contraseña del bot\", \"placeholder\": \"contraseña_del_bot\", \"required\": true}]', 128, 'free', 'medium', 'matrix,nio,python,descentralizado,e2ee,cifrado,chat', NULL, 'https://github.com/poljar/matrix-nio', '1. Crea una cuenta de bot en tu homeserver Matrix\n2. Configura homeserver, usuario y contraseña\n3. Despliega — incluye un bot de ejemplo que responde a !hola\n4. Abre el Gestor de Archivos para editar bot.py con tu lógica\n5. Reinicia el bot para aplicar cambios\n\n📖 Docs: https://matrix-nio.readthedocs.io/en/latest/examples.html', 1, '/data', 'bot.py', 'pip install matrix-nio --quiet && python /app/bot.py', 'https://matrix-nio.readthedocs.io/en/latest/examples.html', 0, 1, 0, 1, '1.0.0', NULL, 13, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(64, 'python-telegram-bot', 'python-telegram-bot — Framework Telegram', 'Herramienta de referencia para desarrolladores Python que buscan interactuar con la API de Telegram de manera asíncrona y eficiente. Soporte completo de la Bot API, handlers, filtros y conversaciones.', 'Framework Python de referencia para bots Telegram.', 'telegram', 'communication', '🐍', 'python:3.11-slim', NULL, NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 128, 'free', 'easy', 'telegram,python,bot,framework,asincrono,handlers', NULL, 'https://python-telegram-bot.org/', '1. Crea un bot con @BotFather en Telegram y copia el token\n2. Configura el token y despliega\n3. El bot incluye un código de ejemplo funcional (echo bot)\n4. Abre el Gestor de Archivos para editar bot.py con tu lógica\n5. Reinicia el bot para aplicar cambios\n\n📖 Docs: https://docs.python-telegram-bot.org/en/stable/examples.html', 1, '/data', 'bot.py', 'pip install python-telegram-bot --quiet && python /app/bot.py', 'https://docs.python-telegram-bot.org/en/stable/examples.html', 0, 1, 6, 1, '1.0.0', NULL, 14, '2026-04-11 20:48:57', '2026-04-14 21:21:29'),
(65, 'grammy', 'grammY — Framework Telegram Moderno', 'Marco de trabajo moderno y extremadamente rápido para Telegram, diseñado con TypeScript. Experiencia de desarrollo superior con tipos completos, plugins extensibles y escalabilidad horizontal.', 'Framework TypeScript moderno y rápido para Telegram.', 'telegram', 'communication', '🎸', 'node:20-alpine', NULL, NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 128, 'free', 'easy', 'telegram,grammy,typescript,nodejs,moderno,rapido,plugins', NULL, 'https://grammy.dev/', '1. Crea un bot con @BotFather en Telegram y copia el token\n2. Configura el token y despliega\n3. El bot incluye un código de ejemplo funcional (echo bot)\n4. Abre el Gestor de Archivos para editar bot.js con tu lógica\n5. Reinicia el bot para aplicar cambios\n\n📖 Docs: https://grammy.dev/guide/getting-started', 1, '/data', 'bot.js', 'cd /app && npm install grammy 2>/dev/null && node /app/bot.js', 'https://grammy.dev/guide/getting-started', 0, 1, 0, 1, '1.0.0', NULL, 15, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(66, 'telegraf', 'Telegraf — Framework Telegram Node.js', 'Framework de Node.js para bots Telegram con sistema de middleware modular. Facilita la extensión de funcionalidades, manejo de sesiones, escenas y soporte completo de la Bot API.', 'Framework Node.js con middleware para Telegram.', 'telegram', 'communication', '📡', 'node:20-alpine', NULL, NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 128, 'free', 'easy', 'telegram,telegraf,nodejs,middleware,modular,sesiones', NULL, 'https://telegraf.js.org/', '1. Crea un bot con @BotFather en Telegram y copia el token\n2. Configura el token y despliega\n3. El bot incluye un código de ejemplo funcional (echo bot)\n4. Abre el Gestor de Archivos para editar bot.js con tu lógica\n5. Reinicia el bot para aplicar cambios\n\n📖 Docs: https://telegraf.js.org/#md:getting-started', 1, '/data', 'bot.js', 'cd /app && npm install telegraf 2>/dev/null && node /app/bot.js', 'https://telegraf.js.org/#md:getting-started', 0, 1, 0, 1, '1.0.0', NULL, 16, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(67, 'evolution-api-lite', 'Evolution API Lite — WhatsApp Ligero', 'Versión optimizada y de bajo consumo de Evolution API, ideal para servidores con recursos limitados. Funcionalidad esencial de WhatsApp API con menor huella de memoria.', 'WhatsApp API ligera para servidores modestos.', 'whatsapp', 'communication', '🪶', 'node:20-alpine', 'https://github.com/EvolutionAPI/evolution-api-lite', NULL, 'main', '{\"AUTHENTICATION_API_KEY\": \"\", \"SERVER_PORT\": \"8080\"}', '[{\"key\": \"AUTHENTICATION_API_KEY\", \"label\": \"API Key de autenticación\", \"placeholder\": \"tu_api_key_segura\", \"required\": true}]', 128, 'free', 'easy', 'evolution,whatsapp,api,lite,ligero,bajo-consumo', NULL, 'https://github.com/EvolutionAPI/evolution-api-lite', '1. Define una API Key de autenticación\n2. Despliega Evolution API Lite\n3. Vincula tu número de WhatsApp escaneando el QR\n4. Usa la API REST para enviar/recibir mensajes\n5. Menor consumo de recursos que la versión completa\n\n📖 Primeros pasos: https://github.com/EvolutionAPI/evolution-api-lite#readme', 0, NULL, NULL, NULL, 'https://github.com/EvolutionAPI/evolution-api-lite#readme', 0, 1, 0, 1, '1.0.0', NULL, 17, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(68, 'wwebjs', 'whatsapp-web.js — WhatsApp vía Navegador', 'Biblioteca Node.js que emula un navegador para interactuar con WhatsApp Web. Automatización sin depender de la API oficial para empresas. Envío de mensajes, medios, gestión de contactos y grupos.', 'Automatiza WhatsApp emulando el navegador web.', 'whatsapp', 'communication', '🌐', 'node:20-alpine', NULL, NULL, 'main', '{\"SESSION_NAME\": \"lanzabot\", \"HEADLESS\": \"true\"}', '[]', 256, 'starter', 'medium', 'whatsapp,wwebjs,navegador,automatizacion,nodejs,puppeteer', NULL, 'https://wwebjs.dev/', '1. Despliega el bot (no necesita credenciales previas)\n2. Revisa los logs para ver el código QR\n3. Escanea el QR con tu teléfono desde WhatsApp\n4. El bot de ejemplo responde a !hola\n5. Abre el Gestor de Archivos para editar bot.js\n\n📖 Docs: https://wwebjs.dev/guide/', 1, '/data', 'bot.js', 'cd /app && npm install whatsapp-web.js qrcode-terminal 2>/dev/null && node /app/bot.js', 'https://wwebjs.dev/guide/', 0, 1, 0, 1, '1.0.0', NULL, 18, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(69, 'telebot-go', 'Telebot (Go) — Framework Telegram en Go', 'Marco de trabajo para bots de Telegram escrito en Go, diseñado para aplicaciones que requieren alto rendimiento y concurrencia. Binario compilado con mínimo consumo de recursos.', 'Framework Telegram en Go: alto rendimiento y concurrencia.', 'telegram', 'communication', '🐹', 'golang:1.22-alpine', NULL, NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 64, 'free', 'medium', 'telegram,go,golang,rendimiento,concurrencia,compilado', NULL, 'https://github.com/tucnak/telebot', '1. Crea un bot con @BotFather en Telegram y copia el token\n2. Configura el token y despliega\n3. El bot incluye un código de ejemplo en Go (echo bot)\n4. Abre el Gestor de Archivos para editar main.go con tu lógica\n5. Reinicia el bot para aplicar cambios\n\n📖 Docs: https://pkg.go.dev/gopkg.in/telebot.v3', 1, '/data', 'main.go', 'cd /app && go mod init bot 2>/dev/null; go get gopkg.in/telebot.v3 && go run /app/main.go', 'https://pkg.go.dev/gopkg.in/telebot.v3#section-readme', 0, 1, 0, 1, '1.0.0', NULL, 19, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(70, 'matrix-whatsapp-bridge', 'Matrix-WhatsApp Bridge', 'Bot especializado que conecta las redes Matrix y WhatsApp, permitiendo que usuarios de Matrix se comuniquen con contactos de WhatsApp de forma nativa. Sincronización de mensajes, medios y grupos.', 'Puente entre Matrix y WhatsApp bidireccional.', 'matrix', 'communication', '🌉', 'dock.mau.dev/mautrix/whatsapp:latest', NULL, NULL, 'main', '{\"MAUTRIX_WHATSAPP_HOMESERVER_ADDRESS\": \"\", \"MAUTRIX_WHATSAPP_HOMESERVER_DOMAIN\": \"\", \"MAUTRIX_WHATSAPP_APPSERVICE_ADDRESS\": \"http://localhost:29318\"}', '[{\"key\": \"MAUTRIX_WHATSAPP_HOMESERVER_ADDRESS\", \"label\": \"URL del homeserver Matrix\", \"placeholder\": \"https://matrix.tuservidor.com\", \"required\": true}, {\"key\": \"MAUTRIX_WHATSAPP_HOMESERVER_DOMAIN\", \"label\": \"Dominio del homeserver\", \"placeholder\": \"tuservidor.com\", \"required\": true}]', 256, 'starter', 'advanced', 'matrix,whatsapp,bridge,puente,sincronizacion,mensajes', NULL, 'https://github.com/mautrix/whatsapp', '1. Ten un homeserver Matrix funcionando\n2. Configura la dirección y dominio del homeserver\n3. Despliega el bridge\n4. Registra el appservice en tu homeserver\n5. Invita al bot a una sala Matrix y vincula tu WhatsApp\n\n📖 Primeros pasos: https://docs.mau.fi/bridges/go/whatsapp/index.html', 1, '/data', NULL, NULL, 'https://docs.mau.fi/bridges/go/whatsapp/index.html', 0, 1, 0, 1, '1.0.0', NULL, 20, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(71, 'freqtrade', 'Freqtrade — Trading Bot Crypto', 'Bot de trading de criptomonedas altamente configurable. Backtesting, optimización de estrategias con IA y control de operaciones desde Telegram. Soporta múltiples exchanges: Binance, Kraken, OKX, etc.', 'Trading automático de crypto con control desde Telegram.', 'telegram', 'finance', '📈', 'freqtradeorg/freqtrade:stable', NULL, NULL, 'main', '{\"FREQTRADE__EXCHANGE__NAME\": \"binance\", \"FREQTRADE__EXCHANGE__KEY\": \"\", \"FREQTRADE__EXCHANGE__SECRET\": \"\", \"FREQTRADE__TELEGRAM__ENABLED\": \"true\", \"FREQTRADE__TELEGRAM__TOKEN\": \"\", \"FREQTRADE__TELEGRAM__CHAT_ID\": \"\"}', '[{\"key\": \"FREQTRADE__EXCHANGE__KEY\", \"label\": \"API Key del Exchange\", \"placeholder\": \"tu_api_key\", \"required\": true}, {\"key\": \"FREQTRADE__EXCHANGE__SECRET\", \"label\": \"API Secret del Exchange\", \"placeholder\": \"tu_api_secret\", \"required\": true}, {\"key\": \"FREQTRADE__TELEGRAM__TOKEN\", \"label\": \"Token Bot Telegram (para control)\", \"placeholder\": \"123456:ABC...\", \"required\": false}, {\"key\": \"FREQTRADE__TELEGRAM__CHAT_ID\", \"label\": \"Chat ID de Telegram\", \"placeholder\": \"123456789\", \"required\": false}]', 512, 'medium', 'advanced', 'freqtrade,trading,crypto,bitcoin,backtesting,estrategias,binance', NULL, 'https://www.freqtrade.io/', '1. Crea API keys en tu exchange (Binance, Kraken, etc.)\n2. Opcionalmente crea un bot en Telegram para control remoto\n3. Configura las credenciales del exchange\n4. Despliega Freqtrade\n5. Accede al panel web para gestionar estrategias y operaciones\n\n📖 Primeros pasos: https://www.freqtrade.io/en/stable/docker_quickstart/', 1, '/freqtrade/user_data', NULL, NULL, 'https://www.freqtrade.io/en/stable/docker_quickstart/', 1, 1, 0, 1, '1.0.0', NULL, 21, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(72, 'hummingbot', 'Hummingbot — Market Making y Arbitraje', 'Herramienta especializada en market making y arbitraje. Ejecuta estrategias profesionales en más de 40 exchanges. Interfaz de línea de comandos y scripts personalizables en Python.', 'Market making y arbitraje profesional multi-exchange.', 'multi', 'finance', '🐦', 'hummingbot/hummingbot:latest', NULL, NULL, 'main', '{\"EXCHANGE\": \"binance\", \"API_KEY\": \"\", \"API_SECRET\": \"\"}', '[{\"key\": \"API_KEY\", \"label\": \"API Key del Exchange\", \"placeholder\": \"tu_api_key\", \"required\": true}, {\"key\": \"API_SECRET\", \"label\": \"API Secret del Exchange\", \"placeholder\": \"tu_api_secret\", \"required\": true}]', 512, 'medium', 'advanced', 'hummingbot,market-making,arbitraje,trading,exchange,profesional', NULL, 'https://hummingbot.org/', '1. Crea API keys en tu exchange preferido\n2. Configura las credenciales\n3. Despliega Hummingbot\n4. Conecta al contenedor y configura la estrategia\n5. Inicia el bot y monitorea las operaciones\n\n📖 Primeros pasos: https://hummingbot.org/installation/docker/', 1, '/home/hummingbot', NULL, NULL, 'https://hummingbot.org/installation/docker/', 0, 1, 0, 1, '1.0.0', NULL, 22, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(73, 'finrl', 'FinRL — Trading con IA (Deep RL)', 'Biblioteca de aprendizaje por refuerzo profundo para trading financiero. Entrena agentes inteligentes en mercados complejos. Backtesting robusto y soporte para múltiples fuentes de datos de mercado.', 'Entrena agentes de trading con aprendizaje por refuerzo.', 'multi', 'finance', '🧠', 'python:3.11-slim', 'https://github.com/AI4Finance-Foundation/FinRL', 'pip install finrl', 'main', '{\"ALPACA_API_KEY\": \"\", \"ALPACA_API_SECRET\": \"\", \"ALPACA_API_BASE_URL\": \"https://paper-api.alpaca.markets\"}', '[{\"key\": \"ALPACA_API_KEY\", \"label\": \"API Key de Alpaca (u otro broker)\", \"placeholder\": \"PK...\", \"required\": true}, {\"key\": \"ALPACA_API_SECRET\", \"label\": \"API Secret de Alpaca\", \"placeholder\": \"tu_secret\", \"required\": true}]', 1024, 'medium', 'advanced', 'finrl,deep-learning,reinforcement,trading,ia,mercados,python', NULL, 'https://github.com/AI4Finance-Foundation/FinRL', '1. Crea una cuenta en Alpaca Markets (paper trading gratuito)\n2. Obtén tus API keys\n3. Configura las credenciales\n4. Despliega FinRL\n5. Entrena y ejecuta agentes de trading con IA\n\n📖 Primeros pasos: https://github.com/AI4Finance-Foundation/FinRL#quick-start', 0, NULL, NULL, NULL, 'https://github.com/AI4Finance-Foundation/FinRL#quick-start', 0, 1, 0, 1, '1.0.0', NULL, 23, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(74, 'jesse', 'Jesse — Algoritmo de Trading Avanzado', 'Algoritmo de trading avanzado en Python enfocado en robustez de estrategias y precisión de datos de mercado durante backtesting. Motor de ejecución optimizado y sistema de indicadores técnicos completo.', 'Trading algorítmico con backtesting preciso en Python.', 'multi', 'finance', '📊', 'python:3.11-slim', 'https://github.com/jesse-ai/jesse', 'pip install jesse', 'main', '{\"EXCHANGE\": \"binance\", \"EXCHANGE_API_KEY\": \"\", \"EXCHANGE_API_SECRET\": \"\"}', '[{\"key\": \"EXCHANGE_API_KEY\", \"label\": \"API Key del Exchange\", \"placeholder\": \"tu_api_key\", \"required\": true}, {\"key\": \"EXCHANGE_API_SECRET\", \"label\": \"API Secret del Exchange\", \"placeholder\": \"tu_api_secret\", \"required\": true}]', 512, 'medium', 'advanced', 'jesse,trading,algoritmo,backtesting,indicadores,python', NULL, 'https://jesse.ai/', '1. Crea API keys en tu exchange\n2. Configura las credenciales\n3. Despliega Jesse\n4. Accede al panel web para diseñar estrategias\n5. Ejecuta backtesting antes de operar en vivo\n\n📖 Primeros pasos: https://docs.jesse.trade/docs/getting-started/', 0, NULL, NULL, NULL, 'https://docs.jesse.trade/docs/getting-started/', 0, 1, 0, 1, '1.0.0', NULL, 24, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(75, 'superalgos', 'Superalgos — Trading Visual Sin Código', 'Plataforma visual para diseño de estrategias de trading sin necesidad de programación. Construye sistemas complejos de automatización financiera con interfaz gráfica. Comunidad activa con estrategias compartidas.', 'Diseña estrategias de trading visualmente sin código.', 'multi', 'finance', '🎯', 'node:20-alpine', 'https://github.com/Superalgos/Superalgos', NULL, 'main', '{\"EXCHANGE\": \"binance\", \"EXCHANGE_API_KEY\": \"\", \"EXCHANGE_API_SECRET\": \"\"}', '[{\"key\": \"EXCHANGE_API_KEY\", \"label\": \"API Key del Exchange\", \"placeholder\": \"tu_api_key\", \"required\": true}, {\"key\": \"EXCHANGE_API_SECRET\", \"label\": \"API Secret del Exchange\", \"placeholder\": \"tu_api_secret\", \"required\": true}]', 1024, 'medium', 'medium', 'superalgos,trading,visual,nocode,estrategias,comunidad', NULL, 'https://superalgos.org/', '1. Crea API keys en tu exchange (Binance recomendado)\n2. Configura las credenciales\n3. Despliega Superalgos\n4. Accede a la interfaz web gráfica\n5. Diseña estrategias arrastrando componentes\n\n📖 Primeros pasos: https://superalgos.org/community-quick-start-guide.shtml', 0, NULL, NULL, NULL, 'https://superalgos.org/community-quick-start-guide.shtml', 0, 1, 0, 1, '1.0.0', NULL, 25, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(76, 'octobot', 'OctoBot — Trading Intuitivo con IA', 'Bot de trading intuitivo con modos para principiantes y expertos. Estrategias de IA, Grid y DCA con interfaz web moderna. Soporta múltiples exchanges y control vía Telegram.', 'Trading con IA: Grid, DCA y más, para todos los niveles.', 'telegram', 'finance', '🐙', 'drakkarsoftware/octobot:stable', NULL, NULL, 'main', '{\"EXCHANGE\": \"binance\", \"EXCHANGE_API_KEY\": \"\", \"EXCHANGE_API_SECRET\": \"\", \"TELEGRAM_BOT_TOKEN\": \"\", \"TELEGRAM_CHAT_ID\": \"\"}', '[{\"key\": \"EXCHANGE_API_KEY\", \"label\": \"API Key del Exchange\", \"placeholder\": \"tu_api_key\", \"required\": true}, {\"key\": \"EXCHANGE_API_SECRET\", \"label\": \"API Secret del Exchange\", \"placeholder\": \"tu_api_secret\", \"required\": true}, {\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token Bot Telegram (opcional)\", \"placeholder\": \"123456:ABC...\", \"required\": false}]', 512, 'medium', 'medium', 'octobot,trading,ia,grid,dca,principiantes,telegram', NULL, 'https://www.octobot.cloud/', '1. Crea API keys en tu exchange\n2. Opcionalmente crea un bot en Telegram\n3. Configura las credenciales\n4. Despliega OctoBot\n5. Accede al panel web para elegir y configurar estrategias\n\n📖 Primeros pasos: https://www.octobot.cloud/en/guides/octobot-installation/with-docker', 1, '/octobot/user', NULL, NULL, 'https://www.octobot.cloud/en/guides/octobot-installation/with-docker', 1, 1, 0, 1, '1.0.0', NULL, 26, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(77, 'labubu-bot', 'Labubu-bot — Automatización de Compras', 'Bot de automatización de compras diseñado para asegurar artículos de edición limitada en plataformas de e-commerce mediante técnicas de anti-detección. Monitoreo de stock y compra automática.', 'Automatiza compras de artículos limitados.', 'multi', 'finance', '🛍️', 'python:3.11-slim', 'https://github.com/Decodo/Labubu-bot', NULL, 'main', '{\"TARGET_URL\": \"\", \"PROXY_URL\": \"\"}', '[{\"key\": \"TARGET_URL\", \"label\": \"URL del producto objetivo\", \"placeholder\": \"https://tienda.com/producto\", \"required\": true}]', 256, 'starter', 'medium', 'labubu,compras,automatizacion,ecommerce,stock,limitado', NULL, 'https://github.com/Decodo/Labubu-bot', '1. Identifica el producto que quieres monitorear\n2. Configura la URL del producto\n3. Opcionalmente configura un proxy\n4. Despliega el bot\n5. El bot monitoreará el stock y comprará automáticamente\n\n📖 Primeros pasos: https://github.com/Decodo/Labubu-bot#readme', 0, NULL, NULL, NULL, 'https://github.com/Decodo/Labubu-bot#readme', 0, 1, 0, 1, '1.0.0', NULL, 27, '2026-04-11 20:48:57', '2026-04-13 20:12:46');
INSERT INTO `bot_templates` (`id`, `slug`, `name`, `description`, `short_description`, `platform`, `category`, `icon`, `docker_image`, `git_repo_url`, `install_command`, `git_branch`, `default_env_vars`, `required_env_vars`, `ram_mb_min`, `min_plan_slug`, `difficulty`, `tags`, `documentation_url`, `more_info_url`, `setup_instructions`, `needs_storage`, `storage_mount_path`, `starter_filename`, `start_command`, `docs_first_steps_url`, `is_featured`, `is_active`, `install_count`, `auto_update_supported`, `version`, `changelog`, `sort_order`, `created_at`, `updated_at`) VALUES
(78, 'medusa', 'Medusa — E-Commerce Headless', 'Plataforma de comercio headless que permite desplegarla como backend automatizado para gestionar pedidos y catálogos de forma programática. API-first, extensible con plugins y módulos.', 'Backend de e-commerce headless y automatizable.', 'multi', 'finance', '🛒', 'node:20-alpine', 'https://github.com/medusajs/medusa-starter-default', NULL, 'master', '{\"MEDUSA_ADMIN_EMAIL\": \"admin@example.com\", \"MEDUSA_ADMIN_PASSWORD\": \"\", \"DATABASE_URL\": \"\", \"JWT_SECRET\": \"\", \"COOKIE_SECRET\": \"\"}', '[{\"key\": \"MEDUSA_ADMIN_PASSWORD\", \"label\": \"Contraseña del admin\", \"placeholder\": \"contraseña_segura\", \"required\": true}, {\"key\": \"JWT_SECRET\", \"label\": \"JWT Secret (aleatorio)\", \"placeholder\": \"jwt_secret_aleatorio\", \"required\": true}, {\"key\": \"COOKIE_SECRET\", \"label\": \"Cookie Secret (aleatorio)\", \"placeholder\": \"cookie_secret_aleatorio\", \"required\": true}]', 512, 'medium', 'medium', 'medusa,ecommerce,headless,api,pedidos,catalogo,tienda', NULL, 'https://medusajs.com/', '1. Define credenciales de admin y secrets aleatorios\n2. Necesitarás una base de datos PostgreSQL\n3. Despliega Medusa\n4. Accede al panel de administración\n5. Configura productos, precios y canales de venta\n\n📖 Primeros pasos: https://docs.medusajs.com/learn', 1, '/app/medusa/uploads', NULL, NULL, 'https://docs.medusajs.com/learn', 0, 1, 0, 1, '1.0.0', NULL, 28, '2026-04-11 20:48:57', '2026-04-14 22:29:38'),
(79, 'bagisto', 'Bagisto — Marketplace Laravel', 'Sistema de e-commerce basado en Laravel. Facilita la creación de marketplaces automatizados y gestión de múltiples inventarios. Panel de admin completo, pasarelas de pago y multi-idioma.', 'Marketplace e-commerce completo basado en Laravel.', 'multi', 'finance', '🏪', 'node:20-alpine', 'https://github.com/bagisto/bagisto', NULL, 'main', '{\"APP_URL\": \"\", \"DB_HOST\": \"localhost\", \"DB_DATABASE\": \"bagisto\", \"DB_USERNAME\": \"\", \"DB_PASSWORD\": \"\"}', '[{\"key\": \"APP_URL\", \"label\": \"URL de tu tienda\", \"placeholder\": \"https://tienda.tudominio.com\", \"required\": true}, {\"key\": \"DB_USERNAME\", \"label\": \"Usuario de base de datos\", \"placeholder\": \"bagisto_user\", \"required\": true}, {\"key\": \"DB_PASSWORD\", \"label\": \"Contraseña de base de datos\", \"placeholder\": \"contraseña_bd\", \"required\": true}]', 512, 'medium', 'advanced', 'bagisto,laravel,marketplace,ecommerce,inventario,tienda', NULL, 'https://bagisto.com/', '1. Necesitarás una base de datos MySQL/MariaDB\n2. Configura la URL y credenciales de BD\n3. Despliega Bagisto\n4. Ejecuta el asistente de instalación web\n5. Configura productos, categorías y pasarelas de pago\n\n📖 Primeros pasos: https://devdocs.bagisto.com/2.x/introduction/installation.html', 0, NULL, NULL, NULL, 'https://devdocs.bagisto.com/2.x/introduction/installation.html', 0, 1, 0, 1, '1.0.0', NULL, 29, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(80, 'saleor', 'Saleor — E-Commerce Python + GraphQL', 'Plataforma de e-commerce de alto rendimiento construida con Python y GraphQL. Ideal para integraciones con bots de atención al cliente y gestión de ventas. Dashboard moderno y API GraphQL potente.', 'E-commerce alto rendimiento con Python y GraphQL.', 'multi', 'finance', '🎨', 'python:3.11-slim', 'https://github.com/saleor/saleor', NULL, 'main', '{\"SECRET_KEY\": \"\", \"DATABASE_URL\": \"\", \"ALLOWED_HOSTS\": \"*\", \"DEFAULT_CURRENCY\": \"EUR\"}', '[{\"key\": \"SECRET_KEY\", \"label\": \"Clave secreta Django\", \"placeholder\": \"clave_aleatoria_larga\", \"required\": true}, {\"key\": \"DATABASE_URL\", \"label\": \"URL de PostgreSQL\", \"placeholder\": \"postgres://user:pass@host/db\", \"required\": true}]', 512, 'medium', 'advanced', 'saleor,ecommerce,python,graphql,dashboard,tienda,api', NULL, 'https://saleor.io/', '1. Necesitarás PostgreSQL y Redis\n2. Genera una clave secreta aleatoria\n3. Configura la URL de la base de datos\n4. Despliega Saleor\n5. Accede al dashboard de administración\n\n📖 Primeros pasos: https://docs.saleor.io/docs/3.x/setup/docker-compose', 1, '/app/media', NULL, NULL, 'https://docs.saleor.io/docs/3.x/setup/docker-compose', 0, 1, 0, 1, '1.0.0', NULL, 30, '2026-04-11 20:48:57', '2026-04-14 22:29:38'),
(81, 'skyra', 'Skyra — Discord Bot Multipropósito', 'Bot de Discord multipropósito conocido por estabilidad y potencia. Moderación avanzada, sistema de niveles, entretenimiento, logs detallados, sistema de economía virtual y configuración granular por servidor.', 'Bot Discord multipropósito: moderación, niveles y más.', 'discord', 'moderation', '🌟', 'node:20-alpine', 'https://github.com/skyra-project/skyra', NULL, 'main', '{\"DISCORD_TOKEN\": \"\", \"PREFIX\": \"!\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}]', 256, 'starter', 'medium', 'skyra,discord,moderacion,niveles,entretenimiento,multiproposito', NULL, 'https://skyra.pw/', '1. Crea una app y bot en Discord Developer Portal\n2. Activa todos los intents privilegiados\n3. Invita al bot con permisos de administrador\n4. Configura el token\n5. Despliega y usa !help para ver comandos disponibles\n\n📖 Primeros pasos: https://github.com/skyra-project/skyra#readme', 1, '/app/data', NULL, NULL, 'https://github.com/skyra-project/skyra#readme', 1, 1, 0, 1, '1.0.0', NULL, 31, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(82, 'vortex', 'Vortex — Moderación y Anti-Raid Discord', 'Bot de moderación para Discord centrado en eficiencia y seguridad. Logs detallados, herramientas de protección contra incursiones (anti-raid), auto-moderación configurable y sistema de strikes.', 'Moderación eficiente y protección anti-raid para Discord.', 'discord', 'moderation', '🌀', 'node:20-alpine', 'https://github.com/jagrosh/Vortex', NULL, 'main', '{\"DISCORD_TOKEN\": \"\", \"OWNER_ID\": \"\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}, {\"key\": \"OWNER_ID\", \"label\": \"Tu ID de usuario Discord\", \"placeholder\": \"123456789012345678\", \"required\": true}]', 256, 'starter', 'medium', 'vortex,discord,moderacion,antiraid,seguridad,logs,strikes', NULL, 'https://github.com/jagrosh/Vortex', '1. Crea una app y bot en Discord Developer Portal\n2. Activa todos los intents privilegiados\n3. Obtén tu ID de usuario Discord (Modo Desarrollador)\n4. Invita al bot con permisos de administrador\n5. Configura el token y despliega\n\n📖 Primeros pasos: https://github.com/jagrosh/Vortex/wiki/Getting-Started', 0, NULL, NULL, NULL, 'https://github.com/jagrosh/Vortex/wiki/Getting-Started', 0, 1, 0, 1, '1.0.0', NULL, 32, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(83, 'modbot', 'ModBot — Moderación Moderna Discord', 'Herramienta de moderación open source para Discord que aprovecha las últimas funciones de la API: botones, menús contextuales y slash commands. Gestión fluida de infracciones, mutes temporales y bans.', 'Moderación moderna con botones y menús en Discord.', 'discord', 'moderation', '🔨', 'node:20-alpine', 'https://github.com/aternosorg/modbot', NULL, 'main', '{\"DISCORD_TOKEN\": \"\", \"DATABASE_URL\": \"\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}]', 256, 'starter', 'easy', 'modbot,discord,moderacion,slash-commands,botones,aternos', NULL, 'https://github.com/aternosorg/modbot', '1. Crea una app y bot en Discord Developer Portal\n2. Activa intents: Server Members, Message Content\n3. Invita al bot con permisos de moderación\n4. Configura el token\n5. Despliega y usa /setup para configurar\n\n📖 Primeros pasos: https://github.com/aternosorg/modbot#readme', 0, NULL, NULL, NULL, 'https://github.com/aternosorg/modbot#readme', 0, 1, 0, 1, '1.0.0', NULL, 33, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(84, 'draupnir', 'Draupnir — Gestión de Comunidades Matrix', 'Plataforma de gestión de comunidades para Matrix. Protege salas contra abuso mediante listas de baneo compartidas (ban lists). Moderación colaborativa entre múltiples servidores Matrix.', 'Protección contra abuso para comunidades Matrix.', 'matrix', 'moderation', '💍', 'node:20-alpine', 'https://github.com/the-draupnir-project/Draupnir', NULL, 'main', '{\"HOMESERVER_URL\": \"\", \"ACCESS_TOKEN\": \"\", \"MANAGEMENT_ROOM\": \"\"}', '[{\"key\": \"HOMESERVER_URL\", \"label\": \"URL del homeserver Matrix\", \"placeholder\": \"https://matrix.tuservidor.com\", \"required\": true}, {\"key\": \"ACCESS_TOKEN\", \"label\": \"Access Token del bot\", \"placeholder\": \"syt_...\", \"required\": true}, {\"key\": \"MANAGEMENT_ROOM\", \"label\": \"ID de la sala de gestión\", \"placeholder\": \"!abc123:matrix.org\", \"required\": true}]', 256, 'starter', 'advanced', 'draupnir,matrix,moderacion,ban-list,abuso,comunidad', NULL, 'https://github.com/the-draupnir-project/Draupnir', '1. Crea una cuenta de bot en tu homeserver Matrix\n2. Obtén el Access Token del bot\n3. Crea una sala de gestión para comandos\n4. Configura las credenciales\n5. Despliega y el bot protegerá tus salas automáticamente\n\n📖 Primeros pasos: https://the-draupnir-project.github.io/draupnir-documentation/', 0, NULL, NULL, NULL, 'https://the-draupnir-project.github.io/draupnir-documentation/', 0, 1, 0, 1, '1.0.0', NULL, 34, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(85, 'mjolnir', 'Mjolnir — Admin Bot para Matrix', 'Bot de administración para Matrix con interfaz de comandos para gestionar moderación y políticas de seguridad en salas de chat. Soporte para ban lists, protecciones automáticas y auditoría.', 'Administración y moderación avanzada para Matrix.', 'matrix', 'moderation', '🔱', 'node:20-alpine', 'https://github.com/matrix-org/mjolnir', NULL, 'main', '{\"HOMESERVER_URL\": \"\", \"ACCESS_TOKEN\": \"\", \"MANAGEMENT_ROOM\": \"\"}', '[{\"key\": \"HOMESERVER_URL\", \"label\": \"URL del homeserver Matrix\", \"placeholder\": \"https://matrix.tuservidor.com\", \"required\": true}, {\"key\": \"ACCESS_TOKEN\", \"label\": \"Access Token del bot\", \"placeholder\": \"syt_...\", \"required\": true}, {\"key\": \"MANAGEMENT_ROOM\", \"label\": \"ID de la sala de gestión\", \"placeholder\": \"!abc123:matrix.org\", \"required\": true}]', 256, 'starter', 'advanced', 'mjolnir,matrix,administracion,ban-list,seguridad,moderacion', NULL, 'https://github.com/matrix-org/mjolnir', '1. Crea una cuenta de bot en tu homeserver Matrix\n2. Obtén el Access Token del bot\n3. Crea una sala de gestión privada\n4. Invita al bot a la sala\n5. Despliega y gestiona la moderación con comandos\n\n📖 Primeros pasos: https://github.com/matrix-org/mjolnir#setup', 0, NULL, NULL, NULL, 'https://github.com/matrix-org/mjolnir#setup', 0, 1, 0, 1, '1.0.0', NULL, 35, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(86, 'group-butler', 'Group Butler — Gestión de Grupos Telegram', 'Bot veterano de Telegram para gestión de grupos. Reglas automáticas, respuestas inteligentes, anti-spam, mensajes de bienvenida, advertencias y configuración granular por grupo.', 'Gestión automática de grupos Telegram con reglas y anti-spam.', 'telegram', 'moderation', '🤵', 'python:3.11-slim', 'https://github.com/group-butler/GroupButler', NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\", \"ADMIN_CHAT_ID\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 128, 'free', 'easy', 'group-butler,telegram,grupos,moderacion,antispam,bienvenida,reglas', NULL, 'https://github.com/group-butler/GroupButler', '1. Crea un bot con @BotFather en Telegram\n2. Configura el token\n3. Despliega Group Butler\n4. Añade el bot como admin a tus grupos\n5. Usa /help para configurar reglas y respuestas automáticas\n\n📖 Primeros pasos: https://github.com/group-butler/GroupButler#readme', 0, NULL, NULL, NULL, 'https://github.com/group-butler/GroupButler#readme', 1, 1, 0, 1, '1.0.0', NULL, 36, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(87, 'red-discordbot', 'Red — Discord Bot Modular', 'Bot modular para Discord donde los usuarios instalan sus propios complementos (cogs). Personalización total de funciones: moderación, música, juegos, utilidades, y miles de cogs de la comunidad.', 'Bot Discord modular con miles de plugins (cogs).', 'discord', 'moderation', '🔴', 'phasecorex/red-discordbot:latest', NULL, NULL, 'main', '{\"TOKEN\": \"\", \"PREFIX\": \"!\", \"OWNER_ID\": \"\"}', '[{\"key\": \"TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}, {\"key\": \"OWNER_ID\", \"label\": \"Tu ID de usuario Discord\", \"placeholder\": \"123456789012345678\", \"required\": true}]', 512, 'medium', 'medium', 'red,discordbot,modular,cogs,plugins,comunidad,personalizable', NULL, 'https://github.com/Cog-Creators/Red-DiscordBot', '1. Crea una app y bot en Discord Developer Portal\n2. Activa todos los intents privilegiados\n3. Obtén tu ID de usuario Discord\n4. Invita al bot con permisos de administrador\n5. Despliega y usa [p]cog install para añadir módulos\n\n📖 Primeros pasos: https://docs.discord.red/en/stable/install_guides/index.html', 1, '/data', NULL, NULL, 'https://docs.discord.red/en/stable/install_guides/index.html', 1, 1, 0, 1, '1.0.0', NULL, 37, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(88, 'discord-tickets', 'Discord Tickets — Sistema de Soporte', 'Sistema de soporte mediante tickets para Discord. Organiza solicitudes de usuarios en canales privados gestionados por el equipo de moderación. Categorías, prioridades, transcripciones y estadísticas.', 'Sistema de tickets de soporte profesional para Discord.', 'discord', 'moderation', '🎫', 'node:20-alpine', 'https://github.com/discord-tickets/bot', NULL, 'main', '{\"DISCORD_TOKEN\": \"\", \"DB_PROVIDER\": \"sqlite\", \"PORTAL_URL\": \"\"}', '[{\"key\": \"DISCORD_TOKEN\", \"label\": \"Token del Bot de Discord\", \"placeholder\": \"MTIzNDU2...\", \"required\": true}]', 256, 'starter', 'easy', 'discord,tickets,soporte,helpdesk,canales,moderacion', NULL, 'https://discord-tickets.com/', '1. Crea una app y bot en Discord Developer Portal\n2. Activa intents: Server Members, Message Content\n3. Invita al bot con permisos de gestión de canales\n4. Configura el token\n5. Despliega y usa /setup para crear categorías de tickets\n\n📖 Primeros pasos: https://discordtickets.app/getting-started/', 1, '/app/data', NULL, NULL, 'https://discordtickets.app/getting-started/', 1, 1, 0, 1, '1.0.0', NULL, 38, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(89, 'twirapp', 'TwirApp — Bot Completo para Twitch', 'Bot de Twitch completo con panel de control web, sistemas de lealtad, automatización de eventos, comandos personalizados, timers y alertas. Mejora la interacción en streams.', 'Bot Twitch con panel web, lealtad y eventos.', 'twitch', 'moderation', '🎮', 'node:20-alpine', 'https://github.com/twirapp/twir', NULL, 'main', '{\"TWITCH_CLIENT_ID\": \"\", \"TWITCH_CLIENT_SECRET\": \"\", \"TWITCH_BOT_USERNAME\": \"\", \"TWITCH_BOT_ACCESS_TOKEN\": \"\"}', '[{\"key\": \"TWITCH_CLIENT_ID\", \"label\": \"Client ID de Twitch\", \"placeholder\": \"tu_client_id\", \"required\": true}, {\"key\": \"TWITCH_CLIENT_SECRET\", \"label\": \"Client Secret de Twitch\", \"placeholder\": \"tu_client_secret\", \"required\": true}, {\"key\": \"TWITCH_BOT_ACCESS_TOKEN\", \"label\": \"Access Token del Bot\", \"placeholder\": \"oauth:...\", \"required\": true}]', 512, 'medium', 'medium', 'twirapp,twitch,streaming,lealtad,eventos,comandos,panel', NULL, 'https://twir.app/', '1. Registra una app en Twitch Developer Console\n2. Obtén Client ID y Secret\n3. Genera un Access Token para la cuenta del bot\n4. Configura las credenciales\n5. Despliega y accede al panel web para personalizar\n\n📖 Primeros pasos: https://github.com/twirapp/twir#readme', 1, '/app/data', NULL, NULL, 'https://github.com/twirapp/twir#readme', 0, 1, 0, 1, '1.0.0', NULL, 39, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(90, 'engelguard', 'EngelGuard — Moderación Twitch Open Source', 'Bot de moderación profesional para Twitch. Alternativa open source y autohospedada a soluciones comerciales. Filtros de chat, timeouts automáticos, protección contra spam y herramientas de moderación.', 'Moderación profesional open source para Twitch.', 'twitch', 'moderation', '👼', 'node:20-alpine', 'https://github.com/Luca-Pelzer/engelguard', NULL, 'main', '{\"TWITCH_CLIENT_ID\": \"\", \"TWITCH_CLIENT_SECRET\": \"\", \"TWITCH_BOT_TOKEN\": \"\", \"TWITCH_CHANNEL\": \"\"}', '[{\"key\": \"TWITCH_CLIENT_ID\", \"label\": \"Client ID de Twitch\", \"placeholder\": \"tu_client_id\", \"required\": true}, {\"key\": \"TWITCH_CLIENT_SECRET\", \"label\": \"Client Secret de Twitch\", \"placeholder\": \"tu_client_secret\", \"required\": true}, {\"key\": \"TWITCH_CHANNEL\", \"label\": \"Canal de Twitch\", \"placeholder\": \"tu_canal\", \"required\": true}]', 128, 'free', 'easy', 'engelguard,twitch,moderacion,opensource,spam,filtros,chat', NULL, 'https://github.com/Luca-Pelzer/engelguard', '1. Registra una app en Twitch Developer Console\n2. Obtén Client ID y Secret\n3. Indica tu canal de Twitch\n4. Configura las credenciales\n5. Despliega y el bot moderará tu chat automáticamente\n\n📖 Primeros pasos: https://github.com/Luca-Pelzer/engelguard#readme', 0, NULL, NULL, NULL, 'https://github.com/Luca-Pelzer/engelguard#readme', 0, 1, 0, 1, '1.0.0', NULL, 40, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(91, 'mautic', 'Mautic — Automatización de Marketing', 'Plataforma de automatización de marketing open source más importante del mundo. Gestiona campañas de email, redes sociales, segmentación de clientes, landing pages y lead scoring.', 'Marketing automation open source: email, redes y leads.', 'multi', 'marketing', '📧', 'mautic/mautic:latest', NULL, NULL, 'main', '{\"MAUTIC_DB_HOST\": \"\", \"MAUTIC_DB_NAME\": \"mautic\", \"MAUTIC_DB_USER\": \"\", \"MAUTIC_DB_PASSWORD\": \"\", \"MAUTIC_ADMIN_EMAIL\": \"\", \"MAUTIC_ADMIN_PASSWORD\": \"\"}', '[{\"key\": \"MAUTIC_DB_HOST\", \"label\": \"Host de la base de datos\", \"placeholder\": \"mysql-host\", \"required\": true}, {\"key\": \"MAUTIC_DB_USER\", \"label\": \"Usuario de base de datos\", \"placeholder\": \"mautic_user\", \"required\": true}, {\"key\": \"MAUTIC_DB_PASSWORD\", \"label\": \"Contraseña de base de datos\", \"placeholder\": \"contraseña_bd\", \"required\": true}, {\"key\": \"MAUTIC_ADMIN_EMAIL\", \"label\": \"Email del administrador\", \"placeholder\": \"admin@tudominio.com\", \"required\": true}, {\"key\": \"MAUTIC_ADMIN_PASSWORD\", \"label\": \"Contraseña del administrador\", \"placeholder\": \"contraseña_admin\", \"required\": true}]', 512, 'medium', 'medium', 'mautic,marketing,email,campañas,leads,segmentacion,automatizacion', NULL, 'https://www.mautic.org/', '1. Necesitarás una base de datos MySQL\n2. Configura credenciales de BD y admin\n3. Despliega Mautic\n4. Completa el asistente de instalación web\n5. Crea tu primera campaña de email marketing\n\n📖 Primeros pasos: https://docs.mautic.org/en/5.x/getting_started/how_to_install_mautic.html', 1, '/var/www/html/var', NULL, NULL, 'https://docs.mautic.org/en/5.x/getting_started/how_to_install_mautic.html', 1, 1, 0, 1, '1.0.0', NULL, 41, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(92, 'yt-dlp', 'yt-dlp — Descarga de Multimedia', 'Herramienta fundamental para descarga de contenido multimedia de miles de sitios web. Frecuentemente usado como motor de bots de descarga en Telegram y Discord. Soporta YouTube, Vimeo, Twitter y cientos más.', 'Motor de descarga multimedia para bots de Telegram/Discord.', 'multi', 'marketing', '📥', 'python:3.11-slim', 'https://github.com/yt-dlp/yt-dlp', 'pip install yt-dlp', 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\", \"DOWNLOAD_PATH\": \"/downloads\", \"MAX_FILE_SIZE_MB\": \"50\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot (Telegram/Discord)\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": false}]', 256, 'starter', 'easy', 'yt-dlp,descarga,youtube,multimedia,video,audio,telegram,discord', NULL, 'https://github.com/yt-dlp/yt-dlp', '1. Opcionalmente crea un bot en Telegram o Discord\n2. Configura el token del bot\n3. Despliega yt-dlp como servicio\n4. Envía URLs al bot para descargar vídeos/audios\n5. Soporta miles de sitios web\n\n📖 Primeros pasos: https://github.com/yt-dlp/yt-dlp#usage-and-options', 1, '/downloads', NULL, NULL, 'https://github.com/yt-dlp/yt-dlp#usage-and-options', 0, 1, 0, 1, '1.0.0', NULL, 42, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(93, 'stickerify', 'Stickerify — Creador de Stickers Telegram', 'Bot de Telegram que facilita la conversión de imágenes y vídeos al formato de stickers de la plataforma de manera automatizada. Recorte automático, redimensionado y creación de packs.', 'Convierte imágenes y vídeos en stickers de Telegram.', 'telegram', 'marketing', '🎭', 'node:20-alpine', 'https://github.com/Stickerifier/Stickerify', NULL, 'main', '{\"TELEGRAM_BOT_TOKEN\": \"\"}', '[{\"key\": \"TELEGRAM_BOT_TOKEN\", \"label\": \"Token del Bot de Telegram\", \"placeholder\": \"123456:ABC-DEF...\", \"required\": true}]', 128, 'free', 'easy', 'stickerify,telegram,stickers,imagenes,conversion,automatico', NULL, 'https://github.com/Stickerifier/Stickerify', '1. Crea un bot con @BotFather en Telegram\n2. Configura el token\n3. Despliega Stickerify\n4. Envía una imagen al bot\n5. Recibirás el sticker listo para usar o añadir a un pack\n\n📖 Primeros pasos: https://github.com/Stickerifier/Stickerify#readme', 0, NULL, NULL, NULL, 'https://github.com/Stickerifier/Stickerify#readme', 0, 1, 0, 1, '1.0.0', NULL, 43, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(94, 'reddit-video-maker', 'Reddit Video Maker Bot', 'Automatiza la creación de vídeos para redes sociales basados en historias populares de Reddit. Integra narración por voz automática (TTS), capturas de pantalla y edición automática.', 'Crea vídeos automáticos de historias de Reddit.', 'reddit', 'marketing', '🎬', 'python:3.11-slim', 'https://github.com/elebumm/RedditVideoMakerBot', NULL, 'main', '{\"REDDIT_CLIENT_ID\": \"\", \"REDDIT_CLIENT_SECRET\": \"\", \"REDDIT_USERNAME\": \"\", \"REDDIT_PASSWORD\": \"\", \"SUBREDDIT\": \"AskReddit\", \"TTS_VOICE\": \"en_us_male\"}', '[{\"key\": \"REDDIT_CLIENT_ID\", \"label\": \"Client ID de Reddit\", \"placeholder\": \"tu_client_id\", \"required\": true}, {\"key\": \"REDDIT_CLIENT_SECRET\", \"label\": \"Client Secret de Reddit\", \"placeholder\": \"tu_client_secret\", \"required\": true}, {\"key\": \"REDDIT_USERNAME\", \"label\": \"Usuario de Reddit\", \"placeholder\": \"mi_usuario\", \"required\": true}, {\"key\": \"REDDIT_PASSWORD\", \"label\": \"Contraseña de Reddit\", \"placeholder\": \"mi_contraseña\", \"required\": true}]', 512, 'medium', 'medium', 'reddit,video,tts,youtube,tiktok,automatizacion,contenido', NULL, 'https://github.com/elebumm/RedditVideoMakerBot', '1. Crea una app en Reddit (https://www.reddit.com/prefs/apps)\n2. Configura Client ID, Secret y credenciales\n3. Elige el subreddit fuente\n4. Despliega el bot\n5. Los vídeos se generarán automáticamente\n\n📖 Primeros pasos: https://github.com/elebumm/RedditVideoMakerBot#readme', 1, '/results', NULL, NULL, 'https://github.com/elebumm/RedditVideoMakerBot#readme', 0, 1, 0, 1, '1.0.0', NULL, 44, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(95, 'amputatorbot', 'AmputatorBot — Limpiador de URLs', 'Bot esencial para mantener la calidad de enlaces en plataformas sociales. Elimina rastreadores y formatos AMP de URLs compartidas, devolviendo la URL original limpia.', 'Elimina rastreadores AMP de URLs compartidas.', 'reddit', 'marketing', '✂️', 'python:3.11-slim', NULL, NULL, 'main', '{\"REDDIT_CLIENT_ID\": \"\", \"REDDIT_CLIENT_SECRET\": \"\", \"REDDIT_USERNAME\": \"\", \"REDDIT_PASSWORD\": \"\", \"SUBREDDITS\": \"all\"}', '[{\"key\": \"REDDIT_CLIENT_ID\", \"label\": \"Client ID de Reddit\", \"placeholder\": \"tu_client_id\", \"required\": true}, {\"key\": \"REDDIT_CLIENT_SECRET\", \"label\": \"Client Secret de Reddit\", \"placeholder\": \"tu_client_secret\", \"required\": true}, {\"key\": \"REDDIT_USERNAME\", \"label\": \"Usuario de Reddit\", \"placeholder\": \"mi_usuario\", \"required\": true}, {\"key\": \"REDDIT_PASSWORD\", \"label\": \"Contraseña de Reddit\", \"placeholder\": \"mi_contraseña\", \"required\": true}]', 128, 'free', 'easy', 'amputatorbot,reddit,urls,amp,rastreadores,limpieza,privacidad', NULL, 'https://www.amputatorbot.com/', '1. Crea una app en Reddit (reddit.com/prefs/apps)\n2. Configura Client ID, Secret y credenciales\n3. Despliega — incluye un bot de ejemplo básico\n4. Abre el Gestor de Archivos para editar bot.py\n5. Reinicia para aplicar cambios\n\n📖 Docs: https://www.amputatorbot.com/', 1, '/data', 'bot.py', 'pip install praw --quiet && python /app/bot.py', 'https://www.amputatorbot.com/', 0, 1, 0, 1, '1.0.0', NULL, 45, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(96, 'allcontributors-bot', 'AllContributors Bot — Reconocimiento GitHub', 'Automatiza el proceso de reconocer y agradecer a los contribuyentes de proyectos open source directamente desde comentarios de GitHub. Genera tablas de contribuidores y badges.', 'Reconoce contribuyentes en proyectos GitHub automáticamente.', 'other', 'marketing', '🏆', 'node:20-alpine', 'https://github.com/all-contributors/app', NULL, 'main', '{\"GITHUB_TOKEN\": \"\", \"REPO_OWNER\": \"\", \"REPO_NAME\": \"\"}', '[{\"key\": \"GITHUB_TOKEN\", \"label\": \"Token de GitHub (Personal Access)\", \"placeholder\": \"ghp_...\", \"required\": true}, {\"key\": \"REPO_OWNER\", \"label\": \"Propietario del repositorio\", \"placeholder\": \"mi-usuario\", \"required\": true}, {\"key\": \"REPO_NAME\", \"label\": \"Nombre del repositorio\", \"placeholder\": \"mi-proyecto\", \"required\": true}]', 128, 'free', 'easy', 'allcontributors,github,opensource,contribuyentes,reconocimiento', NULL, 'https://allcontributors.org/', '1. Genera un Personal Access Token en GitHub\n2. Indica el repositorio donde reconocer contribuyentes\n3. Despliega el bot\n4. Comenta @all-contributors add @user <tipo> en issues/PRs\n5. El bot actualizará el README con la tabla de contribuyentes\n\n📖 Primeros pasos: https://allcontributors.org/docs/en/bot/usage', 0, NULL, NULL, NULL, 'https://allcontributors.org/docs/en/bot/usage', 0, 1, 0, 1, '1.0.0', NULL, 46, '2026-04-11 20:48:57', '2026-04-14 22:29:38'),
(97, 'kodiak', 'Kodiak — Auto-merge GitHub Bot', 'Bot para GitHub que automatiza la actualización de dependencias y la fusión de pull requests una vez que han pasado todas las pruebas de calidad. Mantiene tus ramas actualizadas.', 'Auto-merge de PRs en GitHub tras pasar tests.', 'other', 'marketing', '🐻', 'python:3.11-slim', 'https://github.com/chdsbd/kodiak', NULL, 'main', '{\"GITHUB_APP_ID\": \"\", \"GITHUB_APP_PRIVATE_KEY\": \"\"}', '[{\"key\": \"GITHUB_APP_ID\", \"label\": \"ID de la GitHub App\", \"placeholder\": \"12345\", \"required\": true}, {\"key\": \"GITHUB_APP_PRIVATE_KEY\", \"label\": \"Private Key de la GitHub App (PEM)\", \"placeholder\": \"-----BEGIN RSA PRIVATE KEY-----...\", \"required\": true}]', 256, 'starter', 'medium', 'kodiak,github,automerge,pr,ci,dependencias,automatizacion', NULL, 'https://kodiakhq.com/', '1. Registra una GitHub App en tu organización\n2. Genera una Private Key\n3. Configura App ID y Private Key\n4. Instala la app en tus repositorios\n5. Añade un .kodiak.toml a tus repos para configurar reglas\n\n📖 Primeros pasos: https://kodiakhq.com/docs/quickstart', 0, NULL, NULL, NULL, 'https://kodiakhq.com/docs/quickstart', 0, 1, 0, 1, '1.0.0', NULL, 47, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(98, 'codecov-bot', 'CodeCov Bot — Cobertura de Código', 'Integra reportes de cobertura de código en proyectos de desarrollo. Asegura que nuevas funciones mantengan altos estándares de calidad. Comentarios automáticos en PRs con cambios en cobertura.', 'Reportes de cobertura de código en PRs de GitHub.', 'other', 'marketing', '📊', 'node:20-alpine', NULL, NULL, 'main', '{\"CODECOV_TOKEN\": \"\", \"GITHUB_TOKEN\": \"\"}', '[{\"key\": \"CODECOV_TOKEN\", \"label\": \"Token de CodeCov\", \"placeholder\": \"uuid-token\", \"required\": true}, {\"key\": \"GITHUB_TOKEN\", \"label\": \"Token de GitHub\", \"placeholder\": \"ghp_...\", \"required\": true}]', 128, 'free', 'easy', 'codecov,cobertura,testing,calidad,github,ci,reportes', NULL, 'https://about.codecov.io/', '1. Registra tu repo en codecov.io y obtén el token\n2. Genera un token de GitHub\n3. Configura credenciales y despliega\n4. El bot incluye un código de ejemplo básico\n5. Abre el Gestor de Archivos para editar bot.js\n\n📖 Docs: https://docs.codecov.com/docs/quick-start', 1, '/data', 'bot.js', 'node /app/bot.js', 'https://docs.codecov.com/docs/quick-start', 0, 1, 0, 1, '1.0.0', NULL, 48, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(99, 'newsy-mastodon', 'Newsy Mastodon — Noticias Tech', 'Bot especializado que publica las noticias más relevantes de plataformas tecnológicas directamente en Mastodon. Curación automática de contenido, programación de publicaciones y hashtags inteligentes.', 'Publica noticias tech automáticamente en Mastodon.', 'mastodon', 'marketing', '📰', 'python:3.11-slim', 'https://github.com/anthonydahanne/newsy-mastodon', NULL, 'main', '{\"MASTODON_INSTANCE\": \"\", \"MASTODON_ACCESS_TOKEN\": \"\", \"NEWS_SOURCES\": \"hackernews,techcrunch\", \"POST_INTERVAL\": \"3600\"}', '[{\"key\": \"MASTODON_INSTANCE\", \"label\": \"URL de tu instancia Mastodon\", \"placeholder\": \"https://mastodon.social\", \"required\": true}, {\"key\": \"MASTODON_ACCESS_TOKEN\", \"label\": \"Access Token de Mastodon\", \"placeholder\": \"tu_access_token\", \"required\": true}]', 128, 'free', 'easy', 'newsy,mastodon,noticias,tech,automatico,rss,publicacion', NULL, 'https://github.com/anthonydahanne/newsy-mastodon', '1. Crea una cuenta de bot en tu instancia Mastodon\n2. Ve a Preferencias > Desarrollo > Nueva aplicación\n3. Copia el Access Token\n4. Elige las fuentes de noticias\n5. Despliega y el bot publicará noticias automáticamente\n\n📖 Primeros pasos: https://github.com/anthonydahanne/newsy-mastodon#readme', 0, NULL, NULL, NULL, 'https://github.com/anthonydahanne/newsy-mastodon#readme', 0, 1, 0, 1, '1.0.0', NULL, 49, '2026-04-11 20:48:57', '2026-04-13 20:12:46'),
(100, 'mastodon-frame-bot', 'MastodonFrameBot — Fotogramas en Mastodon', 'Bot artístico que publica fotogramas secuenciales de películas o series en Mastodon, creando una experiencia visual continua para los seguidores. Configura película, intervalo y calidad.', 'Publica fotogramas de películas en Mastodon.', 'mastodon', 'marketing', '🎞️', 'python:3.11-slim', 'https://github.com/cfultz/MastodonFrameBot', NULL, 'main', '{\"MASTODON_INSTANCE\": \"\", \"MASTODON_ACCESS_TOKEN\": \"\", \"MOVIE_PATH\": \"\", \"FRAME_INTERVAL\": \"300\", \"POST_INTERVAL\": \"3600\"}', '[{\"key\": \"MASTODON_INSTANCE\", \"label\": \"URL de tu instancia Mastodon\", \"placeholder\": \"https://mastodon.social\", \"required\": true}, {\"key\": \"MASTODON_ACCESS_TOKEN\", \"label\": \"Access Token de Mastodon\", \"placeholder\": \"tu_access_token\", \"required\": true}, {\"key\": \"MOVIE_PATH\", \"label\": \"Ruta al archivo de vídeo\", \"placeholder\": \"/data/movie.mp4\", \"required\": true}]', 256, 'starter', 'easy', 'mastodon,fotogramas,pelicula,arte,visual,automatico,bot', NULL, 'https://github.com/cfultz/MastodonFrameBot', '1. Crea una cuenta de bot en tu instancia Mastodon\n2. Ve a Preferencias > Desarrollo > Nueva aplicación\n3. Copia el Access Token\n4. Sube el archivo de vídeo al volumen del contenedor\n5. Despliega y el bot publicará fotogramas periódicamente\n\n📖 Primeros pasos: https://github.com/cfultz/MastodonFrameBot#readme', 1, '/data', NULL, NULL, 'https://github.com/cfultz/MastodonFrameBot#readme', 0, 1, 0, 1, '1.0.0', NULL, 50, '2026-04-11 20:48:57', '2026-04-13 20:12:46');

DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `stripe_invoice_id` varchar(255) DEFAULT NULL,
  `stripe_payment_intent_id` varchar(255) DEFAULT NULL,
  `amount` int(11) NOT NULL DEFAULT 0,
  `currency` varchar(10) DEFAULT 'eur',
  `status` varchar(50) DEFAULT 'pending',
  `description` varchar(500) DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `plans`;
CREATE TABLE `plans` (
  `id` int(11) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `price_monthly` decimal(10,2) NOT NULL DEFAULT 0.00,
  `max_bots` int(11) NOT NULL DEFAULT 1,
  `ram_mb` int(11) NOT NULL DEFAULT 128,
  `disk_gb` int(11) NOT NULL DEFAULT 0,
  `disk_temp_mb` int(11) NOT NULL DEFAULT 0,
  `max_databases` int(11) NOT NULL DEFAULT 0,
  `has_eco_mode` tinyint(1) DEFAULT 0,
  `has_redis` tinyint(1) DEFAULT 0,
  `has_backups` tinyint(1) DEFAULT 0,
  `stripe_price_id` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `sort_order` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `plans` (`id`, `slug`, `name`, `price_monthly`, `max_bots`, `ram_mb`, `disk_gb`, `disk_temp_mb`, `max_databases`, `has_eco_mode`, `has_redis`, `has_backups`, `stripe_price_id`, `is_active`, `sort_order`) VALUES
(1, 'free', 'Free', 0.00, 1, 256, 0, 500, 0, 1, 0, 0, NULL, 1, 1),
(2, 'medium', 'Medium', 11.99, 10, 2560, 40, 0, 2, 0, 0, 0, NULL, 1, 3),
(3, 'starter', 'Starter', 5.99, 4, 1024, 15, 0, 1, 0, 0, 0, NULL, 1, 2),
(4, 'pro', 'Pro', 24.99, 25, 6144, 100, 0, 5, 0, 1, 1, NULL, 1, 4),
(5, 'custom', 'Custom', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 1, 5);

DROP TABLE IF EXISTS `subscriptions`;
CREATE TABLE `subscriptions` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `plan_id` int(11) NOT NULL,
  `stripe_subscription_id` varchar(255) DEFAULT NULL,
  `stripe_customer_id` varchar(255) DEFAULT NULL,
  `status` enum('active','canceled','past_due','trialing','unpaid','free') DEFAULT 'active',
  `current_period_end` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `subscriptions` (`id`, `user_id`, `plan_id`, `stripe_subscription_id`, `stripe_customer_id`, `status`, `current_period_end`, `created_at`, `updated_at`) VALUES
(3, 1, 1, NULL, NULL, 'active', NULL, '2026-03-31 11:02:13', '2026-03-31 11:02:13');

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `avatar` varchar(500) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `google_id` varchar(255) DEFAULT NULL,
  `discord_id` varchar(255) DEFAULT NULL,
  `telegram_id` varchar(255) DEFAULT NULL,
  `stripe_customer_id` varchar(255) DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`id`, `email`, `name`, `avatar`, `password_hash`, `email_verified_at`, `google_id`, `discord_id`, `telegram_id`, `stripe_customer_id`, `is_admin`, `created_at`, `updated_at`) VALUES
(1, 'agmonclus@gmail.com', 'Alfredo Garcia', NULL, '$2y$10$l3qXWqLgN3kDl2vSj1NCMuyCY3pU33ex9OpUc/Dy5SqjAg.6KkIJO', '2026-03-25 18:18:41', NULL, NULL, NULL, NULL, 0, '2026-03-25 18:18:25', '2026-03-31 11:01:19');


ALTER TABLE `auth_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `token` (`token`),
  ADD KEY `idx_user_id` (`user_id`),
  ADD KEY `idx_token` (`token`);

ALTER TABLE `bots`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_user_id` (`user_id`),
  ADD KEY `idx_template_id` (`template_id`);

ALTER TABLE `bot_templates`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`),
  ADD KEY `idx_platform` (`platform`),
  ADD KEY `idx_category` (`category`),
  ADD KEY `idx_featured` (`is_featured`),
  ADD KEY `idx_active` (`is_active`);

ALTER TABLE `payments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_user_id` (`user_id`);

ALTER TABLE `plans`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`);

ALTER TABLE `subscriptions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `plan_id` (`plan_id`),
  ADD KEY `idx_user_id` (`user_id`),
  ADD KEY `idx_stripe_subscription` (`stripe_subscription_id`);

ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`),
  ADD KEY `idx_google_id` (`google_id`),
  ADD KEY `idx_discord_id` (`discord_id`),
  ADD KEY `idx_telegram_id` (`telegram_id`);


ALTER TABLE `auth_tokens`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `bots`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

ALTER TABLE `bot_templates`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

ALTER TABLE `payments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `plans`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

ALTER TABLE `subscriptions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;


ALTER TABLE `auth_tokens`
  ADD CONSTRAINT `auth_tokens_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;

ALTER TABLE `bots`
  ADD CONSTRAINT `bots_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;

ALTER TABLE `payments`
  ADD CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;

ALTER TABLE `subscriptions`
  ADD CONSTRAINT `subscriptions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `subscriptions_ibfk_2` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
